### ISSUE TITLE
Allow plugins from system directories

### ISSUE THREAD

**Issue by mruszczyk** [whipper-team/whipper#135]
Right now all of the logging plugins must be installed to either $XDG_DATA_HOME/whipper/plugins or $HOME/.local/share/whipper/plugins, both of which are (generally) in the users home directory. This is fine for users wishing to install plugins themselves but the purpose of system wide packages is to install for all users on a system so requiring packaged binaries to be placed into a home directory defeats that purpose.

In order to make packaging whipper logging plugins easier I suggest whipper also check system directories for plugins.

**Comment by IvanDSM** [comment]
Agreed, very important feature.

**Comment by RecursiveForest** [comment]
I approve of this suggestion.

**Comment by JoeLametta** [comment]
Are there any system "standard" paths for storing the plugins? (something like XDG ones)

**Comment by mruszczyk** [comment]
I mentioned this on irc this morning, I think the obvious answer is the python2 sitelib, as far as how to locate that on any given system I'm unsure. I know on my system is it /usr/lib/python2.X/site-packages but there may be a way to check for the sitelib and check within that directory. 

http://stackoverflow.com/questions/122327/how-do-i-find-the-location-of-my-python-site-packages-directory

**Comment by Freso** [comment]
morituri at least worked fine if you installed loggers to Python's site-packages directory. Has this really been broken by whipper? (I don't think I've used custom loggers with whipper yet, so I wouldn't know.)
