### ISSUE TITLE
Use the track title instead the recoding title (MusicBrainz related)

### ISSUE THREAD

**Issue by gorgobacka** [whipper-team/whipper#192]
Currently, whipper is using the recording title as "track title". However, this can be different from the correct track title.

This is similar to: https://github.com/JoeLametta/whipper/pull/156

**Comment by MerlijnWajer** [comment]
I am assuming that this is for the track filename, is that correct?

**Comment by MerlijnWajer** [comment]
It's also a task for GCI, btw. So perhaps a student will pick it up.

**Comment by gorgobacka** [comment]
No problem. It should be easy to fix. Check also this PR #156, it was a quite similar task.

**Comment by ultra-programmer** [comment]
Hello! I am a GCI student hoping to help out with this problem. In what specific section(s) of the code do you believe the problem is occurring in?

**Comment by JoeLametta** [comment]
Welcome!
You can start looking at function `_getMetadata` in `/whipper/common/mbngs.py`:
https://github.com/whipper-team/whipper/blob/d5bf83e4ccd4a0ea24a640f22f4fbfc1e2b631f4/whipper/common/mbngs.py#L250

:wink:
