### ISSUE TITLE
`'NoneType' object has no attribute '__getitem__'` after rip with current master (a3e9260)

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#196]
If I rip a disc (using `whipper cd --device='/dev/cdrom' rip --cdr --prompt --working-directory='/tmp/rip-disc.h2w' --output-directory='/home/freso/tmp/'`), I end getting this output after an otherwise successful rip:
```Python traceback
Traceback (most recent call last):                
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.5.1', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/whipper/command/main.py", line 32, in main
    ret = cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/basecommand.py", line 124, in do
    return self.cmd.do()
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 190, in do
    self.doCommand()
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 488, in doCommand
    self.program.verifyImage(self.runner, self.ittoc)
  File "/usr/lib/python2.7/site-packages/whipper/common/program.py", line 588, in verifyImage
    return accurip.verify_result(self.result, responses, checksums)
  File "/usr/lib/python2.7/site-packages/whipper/common/accurip.py", line 237, in verify_result
    _assign_checksums_and_confidences(tracks, checksums, responses)
  File "/usr/lib/python2.7/site-packages/whipper/common/accurip.py", line 190, in _assign_checksums_and_confidences
    track.AR[v]['CRC'] = checksums[v][i]
TypeError: 'NoneType' object has no attribute '__getitem__'
```
```text
> yaourt -Qi whipper-git|grep -i version
Version                : 0.5.1.r68.ga3e9260-1
```

**Comment by RecursiveForest** [comment]
Are there any data tracks?

**Comment by Freso** [comment]
> Are there any data tracks?

No.

**Comment by danadam** [comment]
I have the same problem and my CD has a data track:

    Artist  : Pyotr Ilyich Tchaikovsky, Ludwig van Beethoven; Antal Doráti, Minneapolis Symphony Orchestra
    Title   : Tchaikovsky: 1812 Overture / Tchaikovsky: Capriccio Italien / Beethoven: Wellington's Victory
    Duration: 01:06:03.000
    URL     : https://musicbrainz.org/release/092bcb27-2adb-43ae-93c7-bc53d5f68db3
    Release : 092bcb27-2adb-43ae-93c7-bc53d5f68db3
    Type    : Album
    Barcode : 028943436021
    Cat no  : 434 360-2

    creating output directory ./album/Pyotr Ilyich Tchaikovsky, Ludwig van Beethoven; Antal Doráti, Minneapolis Symphony Orchestra - Tchaikovsky - 1812 Overture - Tchaikovsky - Capriccio Italien - Beethoven - Wellington's Victory
    found Hidden Track One Audio from frame 0 to 31
    Ripping track 0 of 6: 00. Pyotr Ilyich Tchaikovsky, Ludwig van Beethoven; Antal Doráti, Minneapolis Symphony Orchestra - Hidden Track One Audio.flac
    CRCs match for track 0
    Peak level: 0.00%
    Rip quality: 100.00%
    HTOA discarded, contains digital silence
    Ripping track 1 of 6: 01. Peter Ilyich Tchaikovsky - 1812 Festival Overture, op. 49.flac
    ...
    Ripping track 6 of 6: 06. Deems Taylor - Commentary to _Wellington's Victory_.flac
    CRCs match for track 6
    Peak level: 100.00%
    Rip quality: 100.00%
    Traceback (most recent call last):
        ...

**Comment by danadam** [comment]
So I tried again but I enabled debug logs, and with another album I had problems with, Florence + the Machine MTV Unplugged, it showed that it found 5 AccuRip results in the cache. The album has 11 tracks. Cleaning the cache solved the problem for both albums.

**Comment by RecursiveForest** [comment]
That's fascinating, does clearing the cache solve Freso's problem too? (Backup cache contents instead of deleting so we can test further if it does, please.)

**Comment by JoeLametta** [comment]
Any news about this one?

**Comment by MerlijnWajer** [comment]
In the archive fork I broke the cache code since it caused a lot of issues and headaches, to no real gain.
