### ISSUE TITLE
Look into adding more MusicBrainz identifiers to ripped files

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#200]
Look into whether more MusicBrainz identifiers (namely Release Group, Track, and Work) are included in the response whipper currently gets when looking up Releases, if it does, include these MusicBrainz IDs in the tags added to the resulting files. (If the IDs are not included, don't bother asking for more information in the web service request.)

**Comment by Freso** [comment]
AFAICT with the output we're already getting we should be able to save Release Group and Track MBIDs in addition to the rest of what we're currently saving. I'll try and make a PR.

**Comment by JoeLametta** [comment]
@Freso A bit unrelated but I'd like to fix this warning before tagging the next release: 

`INFO:musicbrainzngs:in <ws2:release-group>, uncaught attribute type-id`

**Comment by Freso** [comment]
@JoeLametta Is there an issue for that? If not, you should make an issue for that and label it accordingly and maybe ping me in that instead of in unrelated issues. ;) (Or you could come on IRC and point it out!)

**Comment by JoeLametta** [comment]
> @JoeLametta

I know, was in a hurry (sorry).
