### ISSUE TITLE
Write .toc files in addition to .cue files to support cdrdao and non-compliant .cue sheets

### ISSUE THREAD

**Issue by sphh** [whipper-team/whipper#214]
It would be great if `whipper` could write .toc files natively.

**Motivation**: If you want to write an Audio CD from files previously ripped with `whipper` (where `whipper` writes a [non-compliant .cue sheet](http://wiki.hydrogenaud.io/index.php?title=Cue_sheet#Multiple_files_with_gaps_.28Noncompliant.29)), the following steps are necessary – assuming that the files were saved as .flac (see also #212):

1. Convert all ripped .flac files to .wav files.
2. Replace all ".flac" file endings in the .cue file to ".wav".
3. Convert the .cue file to a .toc file with the help of [mktoc](https://github.com/cmcginty/mktoc).
4. Delete all .wav files generated in step 1.
5. Replace all ".wav" file endings in the .cue file to ".flac".
6. Burn the disk with `cdrdao` and the newly created .toc file.

If `whipper` were able to write .toc files, you would not have to go through the steps 1 to 5 and could burn the CD immediately with `cdrdao`.

**Comment by gorgobacka** [comment]
Isn't there already a parameter for this in whipper?

whipper cd rip **-T** 

`  -T TOC_PICKLE, --toc-pickle TOC_PICKLE
                        pickle to use for reading and writing the TOC
                        (default: None)
`

**Comment by sphh** [comment]
Good idea! I tried `whipper cd rip --toc-pickle my.toc ...`, but the file produced does not resemble a .toc file at all: [ovo.toc.zip](https://github.com/JoeLametta/whipper/files/1677151/ovo.toc.zip)

**Comment by RecursiveForest** [comment]
+1 for adding an option to save the disc toc. I think `-t` would be appropriate.

The `-T / --toc_pickle` command is legacy morituri internals cruft and should be deleted shortly.

**Comment by zuzzurro** [comment]
Isn't this needed for ripping cactus data shield protected CDs?

**Comment by JoeLametta** [comment]
> Isn't this needed for ripping cactus data shield protected CDs?

Don't know: what's special about those CDs?
