### ISSUE TITLE
Add a requirements.txt file

### ISSUE THREAD

**Issue by MerlijnWajer** [whipper-team/whipper#221]
Would love to have this for easy installing in a virtualenv. Most of the dependencies are already in the README and travis CI files

**Comment by JoeLametta** [comment]
Is this enough?

```
musicbrainzngs
mutagen
pycdio>=0.17
setuptools
https://downloads.sourceforge.net/sourceforge/cddb-py/CDDB-1.4.tar.gz
-e git+https://gitlab.gnome.org/GNOME/pygobject.git@c9594b6a91e6ca2086fedec2ed8249e0a9c029fc  # python-gobject-2
```

**Comment by MerlijnWajer** [comment]
I think it lacks a few packages - I will start from a clean virtualenv and see what I can do.

**Comment by JoeLametta** [comment]
> I think it lacks a few packages - I will start from a clean virtualenv and see what I can do.

It surely lacks `requests` (I've just added it).

- I've seen a `cdio` import which I'm not sure if it's provided by `pycdio`.
- In order to run the unit tests `twisted` is required.
- `/misc/offsets.py`, which is not truly part of whipper, imports `BeautifulSoup`.

(I think) that's all folks!

**Comment by RecursiveForest** [comment]
the `cdio` package is provided by `pycdio`-- you can verify this by typing `import cdio; cdio.__file__` into the repl.

I don't think you need `setuptools`, it's included in virtualenvs by default.

Pinning to a particular commit hash is sort of unsavory-- why are we doing this? I've been installing python-gobject2 from my OS package manager without issue: currently on 2.28.6. If possible we should at least grab a tagged release from git if we can't grab a release tarball.

**Comment by RecursiveForest** [comment]
Unfortunately the CDDB tarball is unavailable without javascript anymore (trying wget/curl'ing that URL), so that throws a small wrench into the works.

Additionally, when attempting to install pygobject from source with pip, I receive:
```
    Complete output from command python setup.py egg_info:                                               
    ********************************************************************                                 
    * Building PyGObject using distutils is only supported on windows. *                                 
    * To build PyGObject in a supported way, read the INSTALL file.    *                                 
    ********************************************************************                                 
                                                                                                         
    ----------------------------------------                                                             
Command "python setup.py egg_info" failed with error code 1 in /home/fox/testrequests/src/python-gobject2/
```

**Comment by JoeLametta** [comment]
> Pinning to a particular commit hash is sort of unsavory-- why are we doing this?

That was equivalent to tag `PYGOBJECT_2_28_7` (now edited and marked as such).

> Unfortunately the CDDB tarball is unavailable without javascript anymore (trying wget/curl'ing that URL), so that throws a small wrench into the works.

> Unfortunately the CDDB tarball is unavailable without javascript anymore (trying wget/curl'ing that URL), so that throws a small wrench into the works.

Will see if I find a reliable replacement.

> Additionally, when attempting to install pygobject from source with pip, I receive:

Need to investigate this one...

**Comment by RecursiveForest** [comment]
When I tried to `pip install -r`, the pygobject2 line failed with a message saying one must define the egg name with "#egg=" in the URL. Trying that led to the above PyGObject message, which is their way of encouraging you to install it via your operating system.

I would recommend *not* spending much time on this, as we'd eventually like to get *very* far away from pygobject2, and having a 100% comprehensive requirements.txt file is not required. I'd be happy with one that simply listed (like the one I keep on my computer for when I set up new development environments) everything besides pygobject2. We could even leave a note in the file (and the readme, as we already do) saying to install it via your package manager.

The sourceforge issue is a real one, but one that affects many other projects, so a solution may present itself with time. For now: https://github.com/RecursiveForest/py-cddb/releases/tag/v1.4

**Comment by MerlijnWajer** [comment]
I would leave out the pygobject2 stuff as well. Otherwise, seems good. Yes, we can use @RecursiveForest repo for CDDB - might make more sense.

**Comment by JoeLametta** [comment]
- Removed `setuptools` and `python-gobject-2`.
- Replaced SourceForge's `CDDB` URL with another one (sourced from OpenBSD).
- Added `<2.0.0` version number constrain to `pycdio` dependency (related to #229).

For the future, if we decide to keep using the CDDB dependency, there's also @Freso's Python 3 port of it: [here](https://github.com/Freso/cddb-py).

Here's the updated `requirements.txt` file (still missing version numbers).

```
https://ftp.openbsd.org/pub/OpenBSD/distfiles/py-cddb/CDDB-1.4.tar.gz
musicbrainzngs
mutagen
pycdio>=0.17,<2.0.0
requests
```

**Comment by Freso** [comment]
I'd test my port a bit before relying on my cddb-py port. It is a fully automated and when I played around with it a bit, it didn't really perform as expected, IIRC. (Also, cddb-py doesn't handle Unicode at all. I'm not sure if that somehow magically has come "for free" by porting to Py3 though.)

**Comment by GitHubGeek** [comment]
May I suggest go beyond `requirements.txt` and go with [Pipenv](https://github.com/kennethreitz/pipenv). It gives you free virtualenv managemen and many more.

**Comment by JoeLametta** [comment]
TODO:

- [ ] Check if PyGObject should be added to the `requirements.txt` file.
- [ ] Mention `requirements.txt` in whipper's README.
- [ ] Create PR.
