### ISSUE TITLE
Let `debug musicbrainzngs` look up based on MusicBrainz Release ID in addition to Disc ID

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#251]
whipper has a command for helping to find out what's going on with MusicBrainz release data called  `whipper debug musicbrainzngs` (@RecursiveForest is working on moving/renaming this though). This currently takes a [Disc ID](https://musicbrainz.org/doc/Disc_ID) as its one argument.

Sometimes you already know the specific [Release](https://musicbrainz.org/doc/Release) you want but maybe still get wonky data in whipper, so the obvious thing to do would be look up what data whipper actually receives from MusicBrainz. The `debug musicbrainzngs` command would be the obvious way to do this, I think.

**Comment by RecursiveForest** [comment]
Please see https://github.com/JoeLametta/whipper/pull/249

**Comment by JoeLametta** [comment]
Implemented in #432.
