### ISSUE TITLE
Unable to find offset using specific CD.

### ISSUE THREAD

**Issue by mruszczyk** [whipper-team/whipper#252]
I've been attempting to rip Kendrick Lamars DAMN. and was unable to acquire an offset for any of my CD drives. This happens on the latest versions of libcdio and cd-paranoia. I've attached a logfile of whipper offset find -o 48 with the disc if that is any help. I was able to successfully confirm the offset with another disc just now so it appears to be something with this cd.

I ran the cd-paranoia command from the log file directly and the rip appears successful, but accuraterip-checksum does not confirm it as a matching rip.
[whipper.log.gz](https://github.com/JoeLametta/whipper/files/1782491/whipper.log.gz)

**Comment by RecursiveForest** [comment]
What happens if you use `cdparanoia` instead of `cd-paranoia`-- does accuraterip-checksum return the right values then?

It's expected to not be able to confirm your offset with every possible CD, but we definitely want to keep note of digressions between `cdparanoia` and libcdio's `cd-paranoia`.

**Comment by PascalMinder** [comment]
Isn't this bug the same as #234 

Is anyone working on this? Because I still have the same issue when trying to rip a cd.

**Comment by JoeLametta** [comment]
I think this issue isn't related to #234.
Over a year without replies: closing.
