### ISSUE TITLE
Offset works as intended using EAC but not with whipper

### ISSUE THREAD

**Issue by 38github** [whipper-team/whipper#253]
I trying out whipper and I have setup my HL-DT-STDVDRAM GSA-4167B to use a +667 samples offset. This works great in Windows using EAC and the accuraterip comparisons comes out correct but under Linux using the same offset I can't get any rips correct. I have tried whipper's auto offset finder but it crashes after about thirty different offset tests.

Have someone else than me also experienced that an offset that works under Windows does not work correct under Linux (cdparanoia) and does someone have any clue how I can find out the correct value to use under Linux?

**Comment by MerlijnWajer** [comment]
Offset should be the same. Can you document your cdparanoia version, whipper version, cdrdao version? Possible also post the EAC log and whipper log?

**Comment by 38github** [comment]
Thank you for your reply. I am using Arch Linux and the versions I have are:
cdparanoia 10.2-5
cdrdao 1.2.3-10
whipper-git 0.6.0.r5.g653446a-1

**Comment by 38github** [comment]
Whipper:
```
$ whipper cd rip -o 667
Checking device /dev/sr0
CDDB disc id: c30a260e
MusicBrainz disc id B.XTbm.8rRd516_8.Jn9AERXlAA-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+14+195020+150+13042+24812+36415+50137+65882+82815+92650+104592+122082+134260+148640+161762+177422&tracks=14&id=B.XTbm.8rRd516_8.Jn9AERXlAA-
Disc duration: 00:43:18.266, 14 audio tracks

Matching releases:

Artist  : Ann Beretta
Title   : To All Our Fallen Heroes
Duration: 00:43:18.263
URL     : https://musicbrainz.org/release/d43bc51b-5e08-4949-b309-1e6aa0d3540c
Release : d43bc51b-5e08-4949-b309-1e6aa0d3540c
Type    : Album
Barcode : 763361023421
Cat no  : L234

creating output directory ./album/Ann Beretta - To All Our Fallen Heroes
Ripping track 1 of 14: 01. Ann Beretta - Fire in the Hole.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30322028
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 14 (try 2): 01. Ann Beretta - Fire in the Hole.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30322028
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 14 (try 3): 01. Ann Beretta - Fire in the Hole.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30322028
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 14 (try 4): 01. Ann Beretta - Fire in the Hole.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30322028
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
Ripping track 1 of 14 (try 5): 01. Ann Beretta - Fire in the Hole.flac
WARNING:whipper.program.cdparanoia:file size 0 did not match expected size 30322028
WARNING:whipper.program.cdparanoia:non-integral amount of frames difference
CRITICAL:whipper.command.cd:Giving up on track 1 after 5 times
track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'
```

EAC:```

Exact Audio Copy V1.3 from 2. September 2016

EAC extraheringsloggfil från 5. mars 2018, 17:20

Ann Beretta / To All Our Fallen Heroes...

Använd enhet  : HL-DT-STDVDRAM GSA-4167B   Adapter: 1  ID: 0

Läsmetod                 : Säker
Utnyttja accurate stream : Ja
Motverka ljud-cache      : Nej
Använd C2 pekare         : Ja

Läs-offset-korrigering                         : 667
Läs in i Lead-In och Lead-Out                  : Nej
Fyll upp saknade offset-samplingar med tystnad : Ja
Radera inledande och eftersläpande tysta block : Nej
Nollsamplingar används i CRC-beräkningarna     : Ja
Använt gränssnitt                              : Native Win32 gränssnitt för Win NT & 2000
Gap-hantering                                  : Lägg till föregående spår

Använt output format                  : Användardefinierad Kodare
Vald bit-hastighet                    : 768 kBit/s
Kvalité                               : Hög
Lägg till ID3 tag                     : Nej
Kommandolinjekomprimerare             : C:\Program Files (x86)\Exact Audio Copy\FLAC\FLAC.EXE
Ytterligare kommandoradsinställningar : -6 -V -T "ARTIST=%artist%" -T "TITLE=%title%" -T "ALBUM=%albumtitle%" -T "DATE=%year%" -T "TRACKNUMBER=%tracknr%" -T "GENRE=%genre%" -T "COMMENT=%comment%" -T "BAND=%albuminterpret%" -T "ALBUMARTIST=%albuminterpret%" -T "COMPOSER=%composer%" %haslyrics%--tag-from-file=LYRICS="%lyricsfile%"%haslyrics% -T "DISCNUMBER=%cdnumber%" -T "TOTALDISCS=%totalcds%" -T "TOTALTRACKS=%numtracks%" %hascover%--picture="%coverfile%"%hascover% %source% -o %dest%


TOC på den extraherade CD'n

     Spår |   Start  |   Längd  | Startsektor | Slutsektor 
    -------------------------------------------------------
       1  |  0:00.00 |  2:51.67 |        0    |    12891   
       2  |  2:51.67 |  2:36.70 |    12892    |    24661   
       3  |  5:28.62 |  2:34.53 |    24662    |    36264   
       4  |  8:03.40 |  3:02.72 |    36265    |    49986   
       5  | 11:06.37 |  3:29.70 |    49987    |    65731   
       6  | 14:36.32 |  3:45.58 |    65732    |    82664   
       7  | 18:22.15 |  2:11.10 |    82665    |    92499   
       8  | 20:33.25 |  2:39.17 |    92500    |   104441   
       9  | 23:12.42 |  3:53.15 |   104442    |   121931   
      10  | 27:05.57 |  2:42.28 |   121932    |   134109   
      11  | 29:48.10 |  3:11.55 |   134110    |   148489   
      12  | 32:59.65 |  2:54.72 |   148490    |   161611   
      13  | 35:54.62 |  3:28.60 |   161612    |   177271   
      14  | 39:23.47 |  3:54.48 |   177272    |   194869   


Spår  1

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\01-Ann_Beretta-Fire_In_The_Hole.wav

     För-gap längd  0:00:02.00

     Peak-nivå 100.0 %
     Extraheringshastighet 18.1 X
     Spårkvalité 100.0 %
     Kopiera CRC 171B4710
     Korrekt kopierat (konfidens 2)  [744B227D]  (AR v2)
     Kopia OK

Spår  2

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\02-Ann_Beretta-Eye_For_An_Eye.wav

     Peak-nivå 97.8 %
     Extraheringshastighet 17.3 X
     Spårkvalité 100.0 %
     Kopiera CRC 8A6DDAAE
     Korrekt kopierat (konfidens 2)  [43AA52E8]  (AR v2)
     Kopia OK

Spår  3

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\03-Ann_Beretta-Push_To_Shove.wav

     Peak-nivå 98.7 %
     Extraheringshastighet 17.9 X
     Spårkvalité 100.0 %
     Kopiera CRC 31FB897E
     Korrekt kopierat (konfidens 2)  [1B0AD68F]  (AR v2)
     Kopia OK

Spår  4

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\04-Ann_Beretta-Rumour_Town.wav

     Peak-nivå 99.7 %
     Extraheringshastighet 21.9 X
     Spårkvalité 100.0 %
     Kopiera CRC BA90892F
     Korrekt kopierat (konfidens 2)  [35FA1168]  (AR v2)
     Kopia OK

Spår  5

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\05-Ann_Beretta-Bully_Me_Now.wav

     Peak-nivå 99.9 %
     Extraheringshastighet 20.4 X
     Spårkvalité 100.0 %
     Kopiera CRC 788B21D5
     Korrekt kopierat (konfidens 2)  [22540A28]  (AR v2)
     Kopia OK

Spår  6

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\06-Ann_Beretta-Vengeance.wav

     Peak-nivå 99.9 %
     Extraheringshastighet 22.1 X
     Spårkvalité 100.0 %
     Kopiera CRC BFD1ABBC
     Korrekt kopierat (konfidens 2)  [AB1D6CF6]  (AR v2)
     Kopia OK

Spår  7

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\07-Ann_Beretta-Untitled.wav

     Peak-nivå 99.9 %
     Extraheringshastighet 21.4 X
     Spårkvalité 100.0 %
     Kopiera CRC A94A25A1
     Korrekt kopierat (konfidens 2)  [C095C76C]  (AR v2)
     Kopia OK

Spår  8

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\08-Ann_Beretta-Burning_Bridges.wav

     Peak-nivå 93.6 %
     Extraheringshastighet 20.9 X
     Spårkvalité 100.0 %
     Kopiera CRC 339A69A8
     Korrekt kopierat (konfidens 2)  [1BFA9A5E]  (AR v2)
     Kopia OK

Spår  9

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\09-Ann_Beretta-Brothers_At_Arms.wav

     Peak-nivå 99.7 %
     Extraheringshastighet 25.1 X
     Spårkvalité 100.0 %
     Kopiera CRC 6DB99095
     Korrekt kopierat (konfidens 2)  [839AFD57]  (AR v2)
     Kopia OK

Spår 10

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\10-Ann_Beretta-Like_A_Riot.wav

     Peak-nivå 97.7 %
     Extraheringshastighet 23.3 X
     Spårkvalité 100.0 %
     Kopiera CRC 764BEE3A
     Korrekt kopierat (konfidens 2)  [EC03836A]  (AR v2)
     Kopia OK

Spår 11

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\11-Ann_Beretta-Mad_At_The_World.wav

     Peak-nivå 99.9 %
     Extraheringshastighet 25.2 X
     Spårkvalité 100.0 %
     Kopiera CRC 5A38882B
     Korrekt kopierat (konfidens 2)  [33AF2B2E]  (AR v2)
     Kopia OK

Spår 12

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\12-Ann_Beretta-Haywire.wav

     Peak-nivå 99.6 %
     Extraheringshastighet 24.5 X
     Spårkvalité 99.8 %
     Kopiera CRC 1EA57230
     Korrekt kopierat (konfidens 2)  [7668EDF0]  (AR v2)
     Kopia OK

Spår 13

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\13-Ann_Beretta-Loves_Easy_Tears.wav

     Peak-nivå 99.9 %
     Extraheringshastighet 27.4 X
     Spårkvalité 100.0 %
     Kopiera CRC D2C9112A
     Korrekt kopierat (konfidens 2)  [5DF00C02]  (AR v2)
     Kopia OK

Spår 14

     Filnamn C:\ann_beretta-to_all_our_fallen_heroes-1999\14-Ann_Beretta-Surrender.wav

     Peak-nivå 99.3 %
     Extraheringshastighet 33.0 X
     Spårkvalité 100.0 %
     Kopiera CRC 682C88E6
     Korrekt kopierat (konfidens 2)  [3AEDCF80]  (AR v2)
     Kopia OK


Alla spår korrekt kopierade

Inga fel uppstod

Slut på status rapport

---- CUETools DB Plugin V2.1.6

[CTDB TOCID: jz6BFCjcBCBvcsI0kWrOUSMtzLw-] found
Submit result: jz6BFCjcBCBvcsI0kWrOUSMtzLw- has been confirmed
Track | CTDB Status
  1   | (4/4) Accurately ripped
  2   | (4/4) Accurately ripped
  3   | (4/4) Accurately ripped
  4   | (4/4) Accurately ripped
  5   | (4/4) Accurately ripped
  6   | (4/4) Accurately ripped
  7   | (4/4) Accurately ripped
  8   | (4/4) Accurately ripped
  9   | (4/4) Accurately ripped
 10   | (4/4) Accurately ripped
 11   | (4/4) Accurately ripped
 12   | (4/4) Accurately ripped
 13   | (4/4) Accurately ripped
 14   | (4/4) Accurately ripped
```

**Comment by 38github** [comment]
I tried whipper under Fedora 27 and had the same issue. Also the offset find crashed in Fedora too after a couple of attempts. This is very strange.

**Comment by 38github** [comment]
In dmesg i find the following:

```
[   12.245628] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.245632] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.245634] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.245637] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 ea a0 00 00 02 00
[   12.245639] print_req_error: I/O error, dev sr0, sector 240256
[   12.268445] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.268448] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.268450] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.268452] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 ea a0 00 00 01 00
[   12.268454] print_req_error: I/O error, dev sr0, sector 240256
[   12.268463] Buffer I/O error on dev sr0, logical block 60064, async page read
[   12.287612] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.287614] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.287616] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.287619] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 ea a1 00 00 01 00
[   12.287620] print_req_error: I/O error, dev sr0, sector 240260
[   12.287628] Buffer I/O error on dev sr0, logical block 60065, async page read
[   12.467373] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.467376] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.467378] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.467380] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 02 00
[   12.467382] print_req_error: I/O error, dev sr0, sector 0
[   12.486374] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.486376] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.486378] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.486381] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 01 00
[   12.486382] print_req_error: I/O error, dev sr0, sector 0
[   12.486390] Buffer I/O error on dev sr0, logical block 0, async page read
[   12.505374] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.505376] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.505378] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.505381] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 00 01 00 00 01 00
[   12.505382] print_req_error: I/O error, dev sr0, sector 4
[   12.505389] Buffer I/O error on dev sr0, logical block 1, async page read
[   12.524376] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.524378] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.524381] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.524383] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 01 00
[   12.524384] print_req_error: I/O error, dev sr0, sector 0
[   12.524391] Buffer I/O error on dev sr0, logical block 0, async page read
[   12.543375] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.543378] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.543380] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.543382] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 00 01 00 00 01 00
[   12.543383] print_req_error: I/O error, dev sr0, sector 4
[   12.543391] Buffer I/O error on dev sr0, logical block 1, async page read
[   12.562512] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.562514] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.562516] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.562518] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 00 00 00 00 01 00
[   12.562520] print_req_error: I/O error, dev sr0, sector 0
[   12.562527] Buffer I/O error on dev sr0, logical block 0, async page read
[   12.581660] sr 0:0:1:0: [sr0] tag#0 UNKNOWN(0x2003) Result: hostbyte=0x00 driverbyte=0x08
[   12.581663] sr 0:0:1:0: [sr0] tag#0 Sense Key : 0x5 [current] 
[   12.581665] sr 0:0:1:0: [sr0] tag#0 ASC=0x64 ASCQ=0x0 
[   12.581667] sr 0:0:1:0: [sr0] tag#0 CDB: opcode=0x28 28 00 00 00 00 01 00 00 01 00
[   12.581668] print_req_error: I/O error, dev sr0, sector 4
[   12.581676] Buffer I/O error on dev sr0, logical block 1, async page read
[   12.600649] Buffer I/O error on dev sr0, logical block 0, async page read
[   12.620514] Buffer I/O error on dev sr0, logical block 1, async page read

```

**Comment by 38github** [comment]
I tried morituri in Arch Linux' AUR repo and it recognised the find offset somewhat. Not all tracks are ripped correctly but a few are. I also had to install the package cdparanoia-overread because the last track would not rip other wise.

```
[user@q9550 ~]$ rip cd rip --offset 667    
Checking device /dev/sr0
CDDB disc id: c30a260e                        
MusicBrainz disc id B.XTbm.8rRd516_8.Jn9AERXlAA-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+14+195020+150+13042+24812+36415+50137+65882+82815+92650+104592+122082+134260+148640+161762+177422&tracks=14&id=B.XTbm.8rRd516_8.Jn9AERXlAA-
Disc duration: 00:43:18.266, 14 audio tracks

Matching releases:

Artist  : Ann Beretta
Title   : To All Our Fallen Heroes
Duration: 00:43:18.263
URL     : https://musicbrainz.org/release/d43bc51b-5e08-4949-b309-1e6aa0d3540c
Release : d43bc51b-5e08-4949-b309-1e6aa0d3540c
Type    : Album

** Message: pygobject_register_sinkfunc is deprecated (GstObject)
Output directory /home/user/album/Ann Beretta - To All Our Fallen Heroes already exists
Ripping track 1 of 14: 01. Ann Beretta - Fire in the Hole.flac
Checksums match for track 1                   
Peak level: 100.00 %
Rip quality: 100.00 %
Ripping track 2 of 14: 02. Ann Beretta - Eye for an Eye.flac
Checksums match for track 2                   
Peak level: 98.90 %
Rip quality: 100.00 %
Ripping track 3 of 14: 03. Ann Beretta - Push to Shove.flac
Checksums match for track 3                   
Peak level: 99.38 %
Rip quality: 100.00 %
Ripping track 4 of 14: 04. Ann Beretta - Rumour Town.flac
Checksums match for track 4                   
Peak level: 99.90 %
Rip quality: 100.00 %
Ripping track 5 of 14: 05. Ann Beretta - Bully Me Now.flac
Checksums match for track 5                   
Peak level: 99.96 %
Rip quality: 100.00 %
Ripping track 6 of 14: 06. Ann Beretta - Vengeance.flac
Checksums match for track 6                   
Peak level: 99.95 %
Rip quality: 100.00 %
Ripping track 7 of 14: 07. Ann Beretta - Untitled.flac
Checksums match for track 7                   
Peak level: 99.98 %
Rip quality: 100.00 %
Ripping track 8 of 14: 08. Ann Beretta - Burning Bridges.flac
Checksums match for track 8                   
Peak level: 96.75 %
Rip quality: 100.00 %
Ripping track 9 of 14: 09. Ann Beretta - Brothers at Arms.flac
Checksums match for track 9                   
Peak level: 99.88 %
Rip quality: 100.00 %
Ripping track 10 of 14: 10. Ann Beretta - Like a Riot.flac
Checksums match for track 10                  
Peak level: 98.84 %
Rip quality: 100.00 %
Ripping track 11 of 14: 11. Ann Beretta - Mad at the World.flac
Checksums match for track 11                  
Peak level: 100.00 %
Rip quality: 100.00 %
Ripping track 12 of 14: 12. Ann Beretta - Haywire.flac
Checksums match for track 12                  
Peak level: 99.83 %
Rip quality: 100.00 %
Ripping track 13 of 14: 13. Ann Beretta - Love's Easy Tears.flac
Checksums match for track 13                  
Peak level: 99.97 %
Rip quality: 100.00 %
Ripping track 14 of 14: 14. Ann Beretta - Surrender.flac
Checksums match for track 14                  
Peak level: 99.68 %
Rip quality: 100.00 %
AccurateRip URL http://www.accuraterip.com/accuraterip/7/c/9/dBAR-014-001579c7-00e6dd9f-c30a260e.bin
2 AccurateRip reponses found
Track  1: rip accurate     (max confidence      2) [5449b16e], DB [5449b16e]
Track  2: rip NOT accurate (max confidence      2) [2bfc84b5], DB [43aa52e8]
Track  3: rip accurate     (max confidence      2) [e66838a5], DB [e66838a5]
Track  4: rip NOT accurate (max confidence      2) [cf5a9c81], DB [35fa1168]
Track  5: rip accurate     (max confidence      2) [6e51f5d8], DB [6e51f5d8]
Track  6: rip NOT accurate (max confidence      2) [f84966ad], DB [ab1d6cf6]
Track  7: rip NOT accurate (max confidence      2) [4675637b], DB [c095c76c]
Track  8: rip accurate     (max confidence      2) [9d369326], DB [9d369326]
Track  9: rip NOT accurate (max confidence      2) [4b378e32], DB [839afd57]
Track 10: rip accurate     (max confidence      2) [80b448f7], DB [80b448f7]
Track 11: rip NOT accurate (max confidence      2) [795bbf53], DB [33af2b2e]
Track 12: rip NOT accurate (max confidence      2) [24b05c54], DB [7668edf0]
Track 13: rip accurate     (max confidence      2) [b3bad7f1], DB [b3bad7f1]
Track 14: rip accurate     (max confidence      2) [fb8bb418], DB [fb8bb418]
```

**Comment by 38github** [comment]
Update: Using morituri and AUR package cdparanoid-overread I can rip CDs and they come out as rip accurate. I don't know though why the Ann Beretta album didn't come out fully accurate when it does so in Windows.

**Comment by RecursiveForest** [comment]
I assume the checksums (check with `accuraterip-checksum`, not log files) for the windows rip of the Ann Beretta album are different from the whipper version?

**Comment by 38github** [comment]
Thank you for the reply, RecursiveForest! This is the accurip file:
```
[CUETools log; Date: 2018-03-12 21:18:52; Version: 2.1.6]
[CTDB TOCID: jz6BFCjcBCBvcsI0kWrOUSMtzLw-] found.
Track | CTDB Status
  1   | (5/5) Accurately ripped
  2   | (5/5) Accurately ripped
  3   | (5/5) Accurately ripped
  4   | (5/5) Accurately ripped
  5   | (5/5) Accurately ripped
  6   | (5/5) Accurately ripped
  7   | (5/5) Accurately ripped
  8   | (5/5) Accurately ripped
  9   | (5/5) Accurately ripped
 10   | (5/5) Accurately ripped
 11   | (5/5) Accurately ripped
 12   | (5/5) Accurately ripped
 13   | (5/5) Accurately ripped
 14   | (5/5) Accurately ripped
[AccurateRip ID: 001579c7-00e6dd9f-c30a260e] found.
Track   [  CRC   |   V2   ] Status
 01     [5449b16e|744b227d] (2+2/4) Accurately ripped
 02     [2bfc84b5|43aa52e8] (0+2/2) Accurately ripped
 03     [e66838a5|1b0ad68f] (2+2/4) Accurately ripped
 04     [cf5a9c81|35fa1168] (0+2/2) Accurately ripped
 05     [6e51f5d8|22540a28] (2+2/4) Accurately ripped
 06     [f84966ad|ab1d6cf6] (0+2/2) Accurately ripped
 07     [4675637b|c095c76c] (0+2/2) Accurately ripped
 08     [9d369326|1bfa9a5e] (2+2/4) Accurately ripped
 09     [4b378e32|839afd57] (0+2/2) Accurately ripped
 10     [80b448f7|ec03836a] (2+2/4) Accurately ripped
 11     [795bbf53|33af2b2e] (0+2/2) Accurately ripped
 12     [24b05c54|7668edf0] (0+2/2) Accurately ripped
 13     [b3bad7f1|5df00c02] (2+2/4) Accurately ripped
 14     [fb8bb418|3aedcf80] (2+2/4) Accurately ripped

Track Peak [ CRC32  ] [W/O NULL] 
 --  100,0 [D0F895B7] [677A21C4]           
 01  100,0 [171B4710] [779C1AFC]           
 02   97,8 [8A6DDAAE] [2FC1FF91]           
 03   98,7 [31FB897E] [F1B561E3]           
 04   99,7 [BA90892F] [4EADFFB3]           
 05   99,9 [788B21D5] [612F1DE0]           
 06   99,9 [BFD1ABBC] [4762751B]           
 07   99,9 [A94A25A1] [D18DB3C8]           
 08   93,6 [339A69A8] [A0C2D583]           
 09   99,7 [6DB99095] [EF3404A9]           
 10   97,7 [764BEE3A] [AE1CBA53]           
 11   99,9 [5A38882B] [19ED6FF5]           
 12   99,6 [1EA57230] [91219740]           
 13   99,9 [D2C9112A] [1FBC2EFD]           
 14   99,3 [682C88E6] [94BCA7E6]
```

**Comment by MerlijnWajer** [comment]
Sorry, can you elaborate on which log file is whippers log file here?

**Comment by MerlijnWajer** [comment]
That is, you said that it now works on Linux. Can you post the log from whipper where "it works"?

**Comment by 38github** [comment]
Thank you for the reply, RecursiveForest! This is the accurip file:
[CUETools log; Date: 2018-03-12 21:18:52; Version: 2.1.6]
[CTDB TOCID: jz6BFCjcBCBvcsI0kWrOUSMtzLw-] found.
Track | CTDB Status
  1   | (5/5) Accurately ripped
  2   | (5/5) Accurately ripped
  3   | (5/5) Accurately ripped
  4   | (5/5) Accurately ripped
  5   | (5/5) Accurately ripped
  6   | (5/5) Accurately ripped
  7   | (5/5) Accurately ripped
  8   | (5/5) Accurately ripped
  9   | (5/5) Accurately ripped
 10   | (5/5) Accurately ripped
 11   | (5/5) Accurately ripped
 12   | (5/5) Accurately ripped
 13   | (5/5) Accurately ripped
 14   | (5/5) Accurately ripped
[AccurateRip ID: 001579c7-00e6dd9f-c30a260e] found.
Track   [  CRC   |   V2   ] Status
 01     [5449b16e|744b227d] (2+2/4) Accurately ripped
 02     [2bfc84b5|43aa52e8] (0+2/2) Accurately ripped
 03     [e66838a5|1b0ad68f] (2+2/4) Accurately ripped
 04     [cf5a9c81|35fa1168] (0+2/2) Accurately ripped
 05     [6e51f5d8|22540a28] (2+2/4) Accurately ripped
 06     [f84966ad|ab1d6cf6] (0+2/2) Accurately ripped
 07     [4675637b|c095c76c] (0+2/2) Accurately ripped
 08     [9d369326|1bfa9a5e] (2+2/4) Accurately ripped
 09     [4b378e32|839afd57] (0+2/2) Accurately ripped
 10     [80b448f7|ec03836a] (2+2/4) Accurately ripped
 11     [795bbf53|33af2b2e] (0+2/2) Accurately ripped
 12     [24b05c54|7668edf0] (0+2/2) Accurately ripped
 13     [b3bad7f1|5df00c02] (2+2/4) Accurately ripped
 14     [fb8bb418|3aedcf80] (2+2/4) Accurately ripped

Track Peak [ CRC32  ] [W/O NULL] 
 --  100,0 [D0F895B7] [677A21C4]           
 01  100,0 [171B4710] [779C1AFC]           
 02   97,8 [8A6DDAAE] [2FC1FF91]           
 03   98,7 [31FB897E] [F1B561E3]           
 04   99,7 [BA90892F] [4EADFFB3]           
 05   99,9 [788B21D5] [612F1DE0]           
 06   99,9 [BFD1ABBC] [4762751B]           
 07   99,9 [A94A25A1] [D18DB3C8]           
 08   93,6 [339A69A8] [A0C2D583]           
 09   99,7 [6DB99095] [EF3404A9]           
 10   97,7 [764BEE3A] [AE1CBA53]           
 11   99,9 [5A38882B] [19ED6FF5]           
 12   99,6 [1EA57230] [91219740]           
 13   99,9 [D2C9112A] [1FBC2EFD]           
 14   99,3 [682C88E6] [94BCA7E6]

**Comment by 38github** [comment]
I accidentally closed this issue so I reopened it.

**Comment by JoeLametta** [comment]
This one is probably a duplicate of #234.
