### ISSUE TITLE
Write musicbrainz_discid tag when disc is unknown

### ISSUE THREAD

**Issue by xmixahlx** [whipper-team/whipper#280]
whipper writes the the (useless...) title, artist and album tag fields when the disc is Unknown, but does not write the musicbrainz_id tag field, which would be rather useful.

I resolve this by adding the tag in Ex Falso manually, but it would be nice to avoid hunting down the value and avoid copy+paste errors.

FYI to fix Unknown Disc details: I rename the files, then use a "Tags From Path" formula and "Edit Tags" to review/fix/add. Similar naming and tagging functionality would be nice in whipper.

**Comment by Freso** [comment]
If the disc is otherwise unknown, the only MusicBrainz related ID that makes sense to add is the `musicbrainz_discid`. All the other depend on the disc being known.

**Comment by JoeLametta** [comment]
> If the disc is otherwise unknown, the only MusicBrainz related ID that makes sense to add is the `musicbrainz_discid`. All the other depend on the disc being known.

Understood, thanks!

**Comment by JoeLametta** [comment]
I think it makes sense to always add the `musicbrainz_discid` tag (not only when the disc is unknown).

**Comment by Freso** [comment]
> EDIT: man_facepalming It gets already added (only missing when unknown)

Since https://github.com/thomasvs/morituri/pull/77 - yes. ;)

**Comment by JoeLametta** [comment]
@Freso, @MerlijnWajer I think this [Google Code-In task](https://codein.withgoogle.com/tasks/4942209364262912/) should be closed (already completed). :wink:
