### ISSUE TITLE
Possible HTOA error

### ISSUE THREAD

**Issue by xmixahlx** [whipper-team/whipper#281]
Encountered a disc unable to be ripped by whipper. The disc was ripped without issue by grip 3.9.0. Disc is Orchid - Totality. I actually had access to 3 discs and all had the same issue: seemed to hang during HTOA.

Rip hangs at this output:

WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper cd rip
Using configured read offset 48
Checking device /dev/sr0
Reading TOC...
CDDB disc id: 6808b818
MusicBrainz disc id 2nSvdQL1q_kSACEaJyQnmHOHk80-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+24+230585+63150+73805+78120+83556+88782+91399+95410+104276+107836+114403+118640+125867+136301+148280+159286+169284+177892+184540+190038+198033+205092+214304+217121+221579&tracks=24&id=2nSvdQL1q_kSACEaJyQnmHOHk80-
Disc duration: 00:37:12.466, 24 audio tracks
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

FreeDB identifies disc as Totality / Orchid
output directory /home/mike/Music/Lossless/Unknown Artist/2nSvdQL1q_kSACEaJyQnmHOHk80- already exists
found Hidden Track One Audio from frame 0 to 62999
Ripping track 0 of 24: 00 - Unknown Artist - Hidden Track One Audio.flac
Reading track 0 of 24 (1 of 8) ...   0 %

[whipper.log.gz](https://github.com/JoeLametta/whipper/files/2217495/whipper.log.gz)

**Comment by JoeLametta** [comment]
Thanks for reporting this issue.

Don't know if the disc drive you're using with whipper is capable of ripping HTOAs or there's an issue affecting `cd-paranoia`/`whipper` .
I'd like to see the output of the following command (please test it with the same CD and disc drive):

`cd-paranoia --stderr-progress --sample-offset=48 --force-cdrom-device /dev/sr0 0[00:00:00.00]-0[00:13:59.74] /tmp/tmpHCtnnt.whipper.wav`

**Comment by JoeLametta** [comment]
Bump.

**Comment by JoeLametta** [comment]
No reply in 10 days: closed.
