### ISSUE TITLE
CRITICAL:whipper.command.cd:output directory is a finished rip output directory

### ISSUE THREAD

**Issue by nedab** [whipper-team/whipper#287]
Hey Guys and Girls,

I would love to use this ripper, but after setting it up and ripping the first CD this error comes up.

Here are the facts:

Version:
`whipper 0.7.0`

whipper.conf

[whipper.cd.rip]
`unknown = True`
`output_directory=/stuff/Music/0_new`
`track_template=%%A/%%y - %%d/%%t - %%n  ; note: the format char '%' must be repr
esented '%%'`
`disc_template=%%A - %%d (%%y)`

error output
`CRITICAL:whipper.command.cd:output directory /.../Music/0_new is a finished rip
output directory /.../Music/0_new is a finished rip`

Thanks for the help.

**Comment by JoeLametta** [comment]
Hi, could this occur because in the directory `/stuff/Music/0_new` there's already a folder named `Unknown` containing a rip?
Does this issue exist if you set `disc_template = %(track_template)`?

**Comment by JoeLametta** [comment]
No reply: closed (feel free to reopen).
