### ISSUE TITLE
musicbrainz calculation fails on cd with data tracks that are not positioned at the end

### ISSUE THREAD

**Issue by CaseOf** [whipper-team/whipper#289]
I tried to rip a Microsoft Age of Empires Gold Edition disc containing at first track data about the game, and on following tracks, game's soundtrack.
Ripping failed as following:
```
quentin@gentoo_quentin ~/test $ whipper cd rip -U --cdr
Using configured read offset 6
Checking device /dev/sr0
Reading TOC...
CDDB disc id: d30ee90f
Traceback (most recent call last):
  File "/usr/lib/python-exec/python2.7/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.0', 'console_scripts', 'whipper')()
  File "/usr/lib64/python2.7/site-packages/whipper/command/main.py", line 36, in main
    ret = cmd.do()
  File "/usr/lib64/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib64/python2.7/site-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/lib64/python2.7/site-packages/whipper/command/cd.py", line 107, in do
    self.mbdiscid = self.ittoc.getMusicBrainzDiscId()
  File "/usr/lib64/python2.7/site-packages/whipper/image/table.py", line 343, in getMusicBrainzDiscId
    values = self._getMusicBrainzValues()
  File "/usr/lib64/python2.7/site-packages/whipper/image/table.py", line 458, in _getMusicBrainzValues
    assert not self.tracks[-1].audio
AssertionError
```

**Comment by MerlijnWajer** [comment]
The issue here is that morituri's own "musicbrainz id calculation" fails on CDs with data tracks on special places. For my IA fork I decided it wasn't worth my time fixing the custom calculation, and instead I added this commit: https://git.archive.org/archivecd/morituri/commit/8e108e239b15600315128b2e0cba0d4836f044d7 and set the value using the defacto discid library, which does get it right.

We probably do not want to use this hack, but I'm all for just throwing out the custom calculation code from morituri in favour of libdiscid.

**Comment by JoeLametta** [comment]
> We probably do not want to use this hack, but I'm all for just throwing out the custom calculation code from morituri in favour of libdiscid.

:+1:

**Comment by JoeLametta** [comment]
Related to #170 & #171.

**Comment by anarcat** [comment]
@MerlijnWajer that repository is gone - is there a copy anywhere?

**Comment by MerlijnWajer** [comment]
I think they're doing a migration. It should be up in a few hours. :)

**Comment by anarcat** [comment]
@MerlijnWajer awesome. in the meantime, care the paste the patch somewhere else? :) i'm blocked on this very bug...

**Comment by anarcat** [comment]
i see - that just completely disables the musicbrainz stuff, do i read this right?

**Comment by MerlijnWajer** [comment]
It removes the custom calculation code and instead just uses libdiscid, which works OK.
