### ISSUE TITLE
ripping fails frequently, but not repeatably

### ISSUE THREAD

**Issue by DamonLane** [whipper-team/whipper#290]
Thanks for this tool, I love the no-nonsense focus on high quality output!
I've started to re-rip my collection and whipper has successfully completed 18 album, while failing on 9. That seems like a lot to me. (Later, the same ratio: 40 successful, 20 failed)

When I re-ran one to turn on debugging and logging, I noticed that the track it failed on had been successfully ripped the previous time whipper had tried that album, immediately before. I'm using Whipper version 0.7.0.
Edit:
cdparanoia III release 10.2 (September 11, 2008) ! Ok, maybe that's it. Some other issues mention a patched version of this I think? The package is version 3.10.2-r6 and there's no newer or testing version through Gentoo's normal package management system.

` $ whipper cd rip`
...
```
Ripping track 7 of 12: 07. Nirvana - Territorial Pissings.flac
CRCs match for track 7                            
Peak level: 32022
Rip quality: 100.00%
```

`$ WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper cd rip`
...
```
07. Nirvana - Territorial Pissings.flac: done         
Ripping track 8 of 12: 08. Nirvana - Drain You.flac
Ripping track 8 of 12 (try 2): 08. Nirvana - Drain You.flac
Ripping track 8 of 12 (try 3): 08. Nirvana - Drain You.flac
Ripping track 8 of 12 (try 4): 08. Nirvana - Drain You.flac
Ripping track 8 of 12 (try 5): 08. Nirvana - Drain You.flac
track can't be ripped. Rip attempts number is equal to 'MAX_TRIES'
```

I was thinking about cleaning the discs or the drive to see if that helped, but the inconsistent results make me suspicious of the programs. Ideas? Things I can try?

[whipper.log.gz](https://github.com/JoeLametta/whipper/files/2280558/whipper.log.gz)

**Comment by MerlijnWajer** [comment]
Does the CD show any damage? Do you see any drive related errors, perhaps? (in dmesg)

There is nothing in whipper itself that could cause unreproducible rips.

**Comment by MerlijnWajer** [comment]
By the way, there is a open PR with gentoo to get whipper in portage.

**Comment by xmixahlx** [comment]
What are the physical condition of the discs that fail?

Check the error messages again. From your OP, it only looks like track 8 had errors ripping, not 7. You can clean the disc and whipper can continue the rip where it left off (assuming you tell it the same disc release, etc.).

I have had very few albums out of hundreds that had errors ripping while the CD appeared undamaged. Those discs also skipped playing in other drives, so I assumed not an issue with whipper.

If you can see daylight through the disc or there is a physical obstruction, whipper probably can't help there...

**Comment by DamonLane** [comment]
The 20 discs that failed mostly have a scratch or scuff or two but look no worse than the 40 that were successful. They are drying off after a bath now, before trying again. Some of the failed ones look perfect. Thanks for letting me know that problem is probably outside whipper. I am not sure how all the various programs are working together and haven't used CDs much in a long time so don't know where to look for problems.

I retried one of the ones that had failed to look for drive errors. It failed again and then I searched dmesg for 'sr'. Only the initial boot up messages came back: 
```
[    1.299603] sr 1:0:0:0: [sr0] scsi3-mmc drive: 24x/24x writer cd/rw xa/form2 cdda tray
[    1.302151] sr 1:0:0:0: Attached scsi CD-ROM sr0
[    1.302253] sr 1:0:0:0: Attached scsi generic sg1 type 5
```
Maybe it is the discs though, because the few times I've wanted a failed run, like above, I get failure reliably from the discs that failed the first time. It's weird when the track that causes the first failure works correctly the second time, which I've noticed at least twice.

There is another package in Gentoo's portage that may be related to this or other issues involving these two options: app-eselect/eselect-cdparanoia: 
```
Available cdparanoia binary implementations:
  [1]   cdparanoia-paranoia
  [2]   libcdio-paranoia *
```
I don't know the difference between these. After I switched that to [2], two discs that had already failed, failed again, and two discs I hadn't tried also failed. I switched back to [1] and one disc I hadn't tried yet worked and two disc that hadn't worked before and I washed between the last test and this still didn't work. 

They are old CDs, but taken care of better than average, spending their lives in cases, and all have previously been ripped to medium high quality ogg vorbis. Some may have had small playback problems but not 1/3 of my discs!

**Comment by DamonLane** [comment]
Hi, to followup on this, I can say the major problem seems to be the drive itself that was maybe damaged. (Although we hadn't found any I/O errors.) Happily, this is a thinkpad with an ultrabay, so I bought a replacement drive off eBay for $12, swapped it in seconds and viola, about 2/3 of the previously rejected CDs were successfully ripped, and more than a dozen of the rest of my collection, that I hadn't tried yet, have ripped successfully often with max or very high confidence reported.
