### ISSUE TITLE
use standard logging

### ISSUE THREAD

**Issue by anarcat** [whipper-team/whipper#303]
whipper currently writes its error messages and output all jumbled up together on stdout, through the `Program._stdout` file handler. This is useful because it could allow some tests to parse the output of the program and verify things are working okay. That is not currently being used however, so it's unclear to me why this construct is present at all - the only test I could find that would use something like this `TestAccurateRipReport` and it directly hijacks `sys.stdout` and does not touch directly the `Program._stdout` handler.

So I would recommend switching to using the [logging](https://docs.python.org/3/library/logging.html) module. It's standard, well known and expected in Python programs. As a bonus, all messages will be written on stderr (as they should). logfile, syslog and other handlers support becomes trivial to implement as well. The conversion should be easy: just change:

    self._stdout.write("foo %s\n", bar)

to:

    logging.info("foo %s", bar)

or:

    logging.warning....

Depending on the severity level.

How does that sound?

**Comment by MerlijnWajer** [comment]
Sounds good to me if we can get rid of the flog dependency.

**Comment by JoeLametta** [comment]
@anarcat :ok_hand:

**Comment by JoeLametta** [comment]
/remind me "to review this issue" in 12 hours
