### ISSUE TITLE
Make 0.7.1 release (before GCI 😅)

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#312]
There have been [a number of smaller changes to whipper since the 0.7.0 release](https://github.com/whipper-team/whipper/compare/v0.7.0...master), it might be nice to roll those into a 0.7.1 release.

Also, Google Code-in starts in 20 hours, so it might also be nice to do a release before then, since we'll hopefully have a number of MusicBrainz integration contributions coming from that, and a 0.7.1 point would be nicer to compare with than the current 0.7.0 one. :sweat_smile:

(This would also be a nice excuse for package maintainers to update the URLs in/for their packages to the new https://github.com/whipper-team/whipper address. :))

**Comment by MerlijnWajer** [comment]
+1

**Comment by JoeLametta** [comment]
Great suggestion!
Will tag a new release in a few minutes...

P.S.: Excited for the GCI event :tada:

**Comment by JoeLametta** [comment]
Done!

[v0.7.1](https://github.com/whipper-team/whipper/releases/tag/v0.7.1)
