### ISSUE TITLE
PathFilter questions

### ISSUE THREAD

**Issue by q3cpma** [whipper-team/whipper#313]
Hello,

as a POSIX OS user, I'm wondering about the forced character stripping in paths, and am confused at the PathFilter class in path.py:
* What are these "separators" (: and |) and why are they stripped?
* Same for "special" characters, since fat is already here. 

I'm thinking about replacing everything but quotes by "POSIX" and "vfat", while having a configuration option for adding an additional string of characters to replace and maybe another for the fallback character.

**Comment by MerlijnWajer** [comment]
This looks weird indeed. The unicode quoting code is also something we can get rid of, I think.

**Comment by q3cpma** [comment]
On Tue, Oct 23, 2018 at 03:11:10AM -0700, Merlijn Wajer wrote:
> This looks weird indeed. The unicode quoting code is also something we can get rid of, I think.
>
> --
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/whipper-team/whipper/issues/313#issuecomment-432185673

What about something like this? This would leave only the configuration
question (autodetect during the first run and store in the config file?)


diff --git a/whipper/common/path.py b/whipper/common/path.py
index a5d0eb4..2b0fba9 100644
--- a/whipper/common/path.py
+++ b/whipper/common/path.py
@@ -21,47 +21,24 @@
 import re


+POSIX = 0
+MACOS = 1
+WINDOWS = 2
+
 class PathFilter(object):
     """
     I filter path components for safe storage on file systems.
     """

-    def __init__(self, slashes=True, quotes=True, fat=True, special=False):
+    def __init__(self, os=POSIX):
         """
-        @param slashes: whether to convert slashes to dashes
-        @param quotes:  whether to normalize quotes
-        @param fat:     whether to strip characters illegal on FAT filesystems
-        @param special: whether to strip special characters
+        @param os: the path character set restrictions to use
         """
-        self._slashes = slashes
-        self._quotes = quotes
-        self._fat = fat
-        self._special = special
+        self._os = os

     def filter(self, path):
-        if self._slashes:
-            path = re.sub(r'[/\\]', '-', path, re.UNICODE)
-
-        def separators(path):
-            # replace separators with a space-hyphen or hyphen
-            path = re.sub(r'[:]', ' -', path, re.UNICODE)
-            path = re.sub(r'[\|]', '-', path, re.UNICODE)
-            return path
-
-        # change all fancy single/double quotes to normal quotes
-        if self._quotes:
-            path = re.sub(ur'[\xc2\xb4\u2018\u2019\u201b]', "'", path,
-                          re.UNICODE)
-            path = re.sub(ur'[\u201c\u201d\u201f]', '"', path, re.UNICODE)
-
-        if self._special:
-            path = separators(path)
-            path = re.sub(r'[\*\?&!\'\"\$\(\)`{}\[\]<>]',
-                          '_', path, re.UNICODE)
-
-        if self._fat:
-            path = separators(path)
-            # : and | already gone, but leave them here for reference
-            path = re.sub(r'[:\*\?"<>|"]', '_', path, re.UNICODE)
-
-        return path
+        if self._os == POSIX or self._os == MACOS:
+            repl = r'/'
+        else:
+            repl = r'[/\\:*?"<>|]'
+        return re.sub(repl, '_', path, re.UNICODE)

**Comment by MerlijnWajer** [comment]
I think you can use sys.platform for that

**Comment by JoeLametta** [comment]
@q3cpma Let me quote you to have the diff formatted in a code block:

```diff
diff --git a/whipper/common/path.py b/whipper/common/path.py
index a5d0eb4..2b0fba9 100644
--- a/whipper/common/path.py
+++ b/whipper/common/path.py
@@ -21,47 +21,24 @@
 import re


+POSIX = 0
+MACOS = 1
+WINDOWS = 2
+
 class PathFilter(object):
     """
     I filter path components for safe storage on file systems.
     """

-    def __init__(self, slashes=True, quotes=True, fat=True, special=False):
+    def __init__(self, os=POSIX):
         """
-        @param slashes: whether to convert slashes to dashes
-        @param quotes:  whether to normalize quotes
-        @param fat:     whether to strip characters illegal on FAT filesystems
-        @param special: whether to strip special characters
+        @param os: the path character set restrictions to use
         """
-        self._slashes = slashes
-        self._quotes = quotes
-        self._fat = fat
-        self._special = special
+        self._os = os

     def filter(self, path):
-        if self._slashes:
-            path = re.sub(r'[/\\]', '-', path, re.UNICODE)
-
-        def separators(path):
-            # replace separators with a space-hyphen or hyphen
-            path = re.sub(r'[:]', ' -', path, re.UNICODE)
-            path = re.sub(r'[\|]', '-', path, re.UNICODE)
-            return path
-
-        # change all fancy single/double quotes to normal quotes
-        if self._quotes:
-            path = re.sub(ur'[\xc2\xb4\u2018\u2019\u201b]', "'", path,
-                          re.UNICODE)
-            path = re.sub(ur'[\u201c\u201d\u201f]', '"', path, re.UNICODE)
-
-        if self._special:
-            path = separators(path)
-            path = re.sub(r'[\*\?&!\'\"\$\(\)`{}\[\]<>]',
-                          '_', path, re.UNICODE)
-
-        if self._fat:
-            path = separators(path)
-            # : and | already gone, but leave them here for reference
-            path = re.sub(r'[:\*\?"<>|"]', '_', path, re.UNICODE)
-
-        return path
+        if self._os == POSIX or self._os == MACOS:
+            repl = r'/'
+        else:
+            repl = r'[/\\:*?"<>|]'
+        return re.sub(repl, '_', path, re.UNICODE)

```
