### ISSUE TITLE
Can not install

### ISSUE THREAD

**Issue by ekudritski** [whipper-team/whipper#314]
Can somebody tell me how to install?

**Comment by MerlijnWajer** [comment]
Install on what system, did you check out the readme?

**Comment by ekudritski** [comment]
It is fresh Ubuntu.  I never get hit with libcdio version.

**Comment by JoeLametta** [comment]
> It is fresh Ubuntu. I never get hit with libcdio version.

If your distribution is Ubuntu I think it would be easier for you to run whipper as a [Docker](https://docs.docker.com/install/linux/docker-ce/ubuntu/#extra-steps-for-aufs) container: instructions [HERE](https://github.com/whipper-team/whipper#docker).

**Comment by JoeLametta** [comment]
No reply: issue closed (feel free to reopen it).
