### ISSUE TITLE
Add whipper to Hydrogen Audio wiki's "Comparison of CD rippers"

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#317]
https://wiki.hydrogenaud.io/index.php?title=Comparison_of_CD_rippers has morituri but not whipper. I reckon that adding whipper would be mostly a straight copy of the morituri info, but I think there are also some changed (improvements) since the morituri days, and I'm not completely clear on what those are, so I don't feel qualified to add it myself.

**Comment by JoeLametta** [comment]
Done! 

:wink:
