### ISSUE TITLE
Save ISRCs from CD TOC

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#320]
If the CD TOC contains ISRCs we should save those in the ripped file metadata. We're already reading the CD TOC and thus getting the ISRCs, so we may as well store them.

**Comment by JoeLametta** [comment]
Good suggestion!

BTW: ISRC values, if available, are already included in whipper's generated cue sheets, right?

**Comment by jtl999** [comment]
Yes...

```
REM DISCID FE0F0510
REM COMMENT "whipper 0.7.0"
PERFORMER "Arcade Fire"
TITLE "The Suburbs"
FILE "The Suburbs/01 - The Suburbs.flac" WAVE
  TRACK 01 AUDIO
    PERFORMER "Arcade Fire"
    TITLE "The Suburbs"
    ISRC GBUM71018417
    INDEX 01 00:00:00
FILE "The Suburbs/02 - Ready to Start.flac" WAVE
  TRACK 02 AUDIO
    PERFORMER "Arcade Fire"
    TITLE "Ready To Start "
    ISRC GBUM71021615
    INDEX 01 00:00:00
```

**Comment by JoeLametta** [comment]
> Also noticed that whipper is using `--fast-toc` for `cdrdao`.

Actually I think we're using both:

https://github.com/whipper-team/whipper/blob/542e07144385638e5813148c25cf2d5e9e772412/whipper/command/cd.py#L97-L141

Perhaps we should remove the `fast-toc` phase if we need reliable ISRCs for MusicBrainz metadata selection (and that seeems to cause "ISRC  bleeding").

**Comment by jtl999** [comment]
I like the "slow" cdrdao reading TOC phase as I find the Q sub-channel CRC error log a good heuristic of how possibly damaged a CD is before ripping. Probably a "misuse" of this feature but it works for me. 

I was thinking for #299 of parsing the cdrdao read-toc output and printing a representation of the TOC data to console/log and something like `Track %i done, found %i Q sub-channels with CRC errors` for each track?
