### ISSUE TITLE
Hang on cd rip

### ISSUE THREAD

**Issue by YaLTeR** [whipper-team/whipper#326]
Whipper hangs after printing the matched release info. This is the last line in the log:
```
DEBUG:whipper.program.cdrdao:executing ['cdrdao', 'read-toc', '--device', '/dev/sr1', u'/tmp/tmpduaxWy.cdrdao.read-toc.whipper']
```
My drive is spinning up and stopping every couple of seconds until I Ctrl-C out of whipper.

Earlier I was able to `whipper offset find` successfully with the same CD, which as far as I can tell involved ripping the tracks too.

[whipper.log from `whipper cd rip`](https://gist.github.com/YaLTeR/c3965051b1a7350261ff97fce852a863)

Arch Linux x64, whipper 0.7.2.

**Comment by JoeLametta** [comment]
> My drive is spinning up and stopping every couple of seconds until I Ctrl-C out of whipper.

Thanks for the issue report.
How long have you waited before saying that whipper hangs? The phase preceding the actual ripping of the audio tracks, phase which is handled by cdrdao, may take a few minutes as the entire CD is scanned to detect pregaps, disc layout and subcode flags.
Please try to rip the same CD again and report if whipper remains in that phase for more than 30 minutes.

Cheers,
Joe

**Comment by YaLTeR** [comment]
Oh, I waited for about 5 mins since the offset find started so quickly. Sorry, I'm very new to ripping, I will try waiting more tomorrow.

**Comment by YaLTeR** [comment]
Yep, after a longer wait it started. Thanks! Perhaps it would be a good idea to print a message right before this long process which says it might take a long time?

**Comment by JoeLametta** [comment]
> Yep, after a longer wait it started. Thanks!

Glad to hear this. :+1: 

> Perhaps it would be a good idea to print a message right before this long process which says it might take a long time?

That's a good suggestion: we're already discussing something similar in #299 :wink:
