### ISSUE TITLE
fedora 29, whipper 0.72, Error While Executing Any Command

### ISSUE THREAD

**Issue by pyropingvin** [whipper-team/whipper#332]
`$  whipper -v`
```python
Traceback (most recent call last):
  File "/usr/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.7.2', 'console_scripts', 'whipper')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 484, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2714, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2332, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2338, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/site-packages/whipper/command/main.py", line 11, in <module>
    from whipper.command import cd, offset, drive, image, accurip, mblookup
  File "/usr/lib/python2.7/site-packages/whipper/command/cd.py", line 22, in <module>
    import cdio
  File "/home/zivan/.local/lib/python2.7/site-packages/cdio.py", line 20, in <module>
    import pycdio
  File "/home/zivan/.local/lib/python2.7/site-packages/pycdio.py", line 35, in <module>
    _pycdio = swig_import_helper()
  File "/home/zivan/.local/lib/python2.7/site-packages/pycdio.py", line 31, in swig_import_helper
    _mod = imp.load_module('_pycdio', fp, pathname, description)
ImportError: libcdio.so.13: cannot open shared object file: No such file or directory
```

**Comment by JoeLametta** [comment]
Thanks for the issue report!
Have you installed whipper on Fedora 29 using the native package provided by the distribution?

In the meantime let's ping @mruszczyk which is whipper's package contributor for Fedora.

**Comment by pyropingvin** [comment]
> Have you installed whipper on Fedora 29 using the native package provided by the distribution?

yes

**Comment by mruszczyk** [comment]
Can you try installing libcdio with dnf? I can check if something changed recently but I thought one of the dependencies pulled it in. I’ll take a look tomorrow to be sure.

**Comment by pyropingvin** [comment]
$ sudo dnf install libcdio
[sudo] password: 
Last metadata expiration check: 0:23:17 ago on Mon 12 Nov 2018 09:14:07 AM CET.
Package libcdio-2.0.0-3.fc29.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!

**Comment by mruszczyk** [comment]
What version of pycdio do you have installed?

**Comment by pyropingvin** [comment]
pycdio-2.0.0-3.fc29.x86_64
this is upgrade from F28, butt I have same problem on F28 with whipper 0.7.0. I just don't ask for help because i have hope when i upgrade to F29 the problem will go away.

**Comment by mruszczyk** [comment]
Did you ever have whipper installed via source or installed pycdio via pip? I would try removing pycdio via dnf, then pip uninstall pycdio then reinstall pycdio from dnf.

**Comment by pyropingvin** [comment]
sudo dnf remove pycdio
Dependencies resolved.
____________________________________________________________
 Package                               Arch    Version          Repository
                                                                           Size
____________________________________________________________
Removing:
 pycdio                                x86_64  2.0.0-3.fc29     @fedora   525 k
Removing dependent packages:
 whipper                               x86_64  0.7.2-3.fc29     @updates  876 k
Removing unused dependencies:
 cdrdao                                x86_64  1.2.3-34.fc29    @fedora   1.6 M
 python2-backports-ssl_match_hostname  noarch  3.5.0.1-10.fc29  @fedora    18 k
 python2-chardet                       noarch  3.0.4-7.fc29     @fedora   906 k
 python2-idna                          noarch  2.7-3.fc29       @fedora   611 k
 python2-ipaddress                     noarch  1.0.18-5.fc29    @fedora   228 k
 python2-musicbrainzngs                noarch  0.5-12.fc29      @fedora   181 k
 python2-pysocks                       noarch  1.6.8-4.fc29     @fedora    80 k
 python2-requests                      noarch  2.20.0-1.fc29    @updates  396 k
 python2-urllib3                       noarch  1.23-4.fc29      @fedora   663 k

Transaction Summary
____________________________________________________________
Remove  11 Packages

Freed space: 6.0 M
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
Erase: whipper-0.7.2-3.fc29.x86_64
  Erasing          : whipper-0.7.2-3.fc29.x86_64                           1/11 
Erase: whipper-0.7.2-3.fc29.x86_64
Erase: python2-requests-2.20.0-1.fc29.noarch
  Erasing          : python2-requests-2.20.0-1.fc29.noarch                 2/11 
Erase: python2-requests-2.20.0-1.fc29.noarch
Erase: python2-urllib3-1.23-4.fc29.noarch
  Erasing          : python2-urllib3-1.23-4.fc29.noarch                    3/11 
Erase: python2-urllib3-1.23-4.fc29.noarch
Erase: python2-backports-ssl_match_hostname-3.5.0.1-10.fc29.noarch
  Erasing          : python2-backports-ssl_match_hostname-3.5.0.1-10.fc    4/11 
Erase: python2-backports-ssl_match_hostname-3.5.0.1-10.fc29.noarch
Erase: python2-ipaddress-1.0.18-5.fc29.noarch
  Erasing          : python2-ipaddress-1.0.18-5.fc29.noarch                5/11 
Erase: python2-ipaddress-1.0.18-5.fc29.noarch
Erase: python2-pysocks-1.6.8-4.fc29.noarch
  Erasing          : python2-pysocks-1.6.8-4.fc29.noarch                   6/11 
Erase: python2-pysocks-1.6.8-4.fc29.noarch
Erase: python2-chardet-3.0.4-7.fc29.noarch
  Erasing          : python2-chardet-3.0.4-7.fc29.noarch                   7/11 
Erase: python2-chardet-3.0.4-7.fc29.noarch
Erase: python2-idna-2.7-3.fc29.noarch
  Erasing          : python2-idna-2.7-3.fc29.noarch                        8/11 
Erase: python2-idna-2.7-3.fc29.noarch
Erase: python2-musicbrainzngs-0.5-12.fc29.noarch
  Erasing          : python2-musicbrainzngs-0.5-12.fc29.noarch             9/11 
Erase: python2-musicbrainzngs-0.5-12.fc29.noarch
Erase: cdrdao-1.2.3-34.fc29.x86_64
  Erasing          : cdrdao-1.2.3-34.fc29.x86_64                          10/11 
Erase: cdrdao-1.2.3-34.fc29.x86_64
Erase: pycdio-2.0.0-3.fc29.x86_64
  Erasing          : pycdio-2.0.0-3.fc29.x86_64                           11/11 
Erase: pycdio-2.0.0-3.fc29.x86_64
  Running scriptlet: pycdio-2.0.0-3.fc29.x86_64                           11/11 
  Verifying        : cdrdao-1.2.3-34.fc29.x86_64                           1/11 
  Verifying        : pycdio-2.0.0-3.fc29.x86_64                            2/11 
  Verifying        : python2-backports-ssl_match_hostname-3.5.0.1-10.fc    3/11 
  Verifying        : python2-chardet-3.0.4-7.fc29.noarch                   4/11 
  Verifying        : python2-idna-2.7-3.fc29.noarch                        5/11 
  Verifying        : python2-ipaddress-1.0.18-5.fc29.noarch                6/11 
  Verifying        : python2-musicbrainzngs-0.5-12.fc29.noarch             7/11 
  Verifying        : python2-pysocks-1.6.8-4.fc29.noarch                   8/11 
  Verifying        : python2-requests-2.20.0-1.fc29.noarch                 9/11 
  Verifying        : python2-urllib3-1.23-4.fc29.noarch                   10/11 
  Verifying        : whipper-0.7.2-3.fc29.x86_64                          11/11 

Removed:
  pycdio-2.0.0-3.fc29.x86_64                                                    
  whipper-0.7.2-3.fc29.x86_64                                                   
  cdrdao-1.2.3-34.fc29.x86_64                                                   
  python2-backports-ssl_match_hostname-3.5.0.1-10.fc29.noarch                   
  python2-chardet-3.0.4-7.fc29.noarch                                           
  python2-idna-2.7-3.fc29.noarch                                                
  python2-ipaddress-1.0.18-5.fc29.noarch                                        
  python2-musicbrainzngs-0.5-12.fc29.noarch                                     
  python2-pysocks-1.6.8-4.fc29.noarch                                           
  python2-requests-2.20.0-1.fc29.noarch                                         
  python2-urllib3-1.23-4.fc29.noarch                                            

Complete!
$ sudo pip uninstall pycdio
Skipping pycdio as it is not installed.

**Comment by JoeLametta** [comment]
Any news about this one?

**Comment by JoeLametta** [comment]
@mruszczyk Any ideas about what may be causing this issue?

**Comment by pyropingvin** [comment]
I find solution. The problem was local not upstream. I noticed in traceback that Whipper try to import some files from local ~/.local/lib/pithon2.7/... directorium. I guess it's a remnant of my previous old Mint installation when I compiled it myself. So I just delete local files and Whipper start to work without problem.
Thanks to everyone.

**Comment by MerlijnWajer** [comment]
Thanks. Perhaps check your PYTHONPATH.
