### ISSUE TITLE
WARNING:whipper.common.program:network error: NetworkError()

### ISSUE THREAD

**Issue by Fitap** [whipper-team/whipper#338]
Using configured read offset 102
Checking device /dev/sr0
Reading TOC...
CDDB disc id: ae0e300d
MusicBrainz disc id FkWwPTqZk1Jv5N9cbdbnTl.1Fgs-
MusicBrainz lookup URL https://musicbrainz.org:80/cdtoc/attach?toc=1+13+272570+182+22507+47247+61192+84425+99592+118525+143270+163280+180732+209475+230070+254780&tracks=13&id=FkWwPTqZk1Jv5N9cbdbnTl.1Fgs-
Disc duration: 01:00:31.840, 13 audio tracks
WARNING:whipper.common.program:network error: NetworkError()
Continuing without metadata
Submit this disc to MusicBrainz at the above URL.

FreeDB identifies disc as Mark Knopfler / Sailing to Philadelphia
CRITICAL:whipper.command.cd:unable to retrieve disc metadata, --unknown not passed

**Comment by jtl999** [comment]
Do you have a working network connection?

**Comment by Fitap** [comment]
I don't know if a site musicbrainz trouble or what.
This issue is solved.

**Comment by JoeLametta** [comment]
> MusicBrainz lookup URL https://musicbrainz.org:80/cdtoc/attach?toc=1+13+272570+182+22507+47247+61192+84425+99592+118525+143270+163280+180732+209475+230070+254780&tracks=13&id=FkWwPTqZk1Jv5N9cbdbnTl.1Fgs-

Well, that MusicBrainz lookup URL isn't OK (HTTPS on port 80 isn't going to work).
