### ISSUE TITLE
Error when parsing log file due to left pad track number

### ISSUE THREAD

**Issue by itismadness** [whipper-team/whipper#340]
Right now, whipper left pads the track numbers out for the TOC and Tracks top-level entries in the YAML log such that each entry is of equal length. When parsing it, the [YAML Spec](http://yaml.org/type/int.html) specifies that the values 01 to 07 be treated as octals and thus how 08 and 09 parses is somewhat undefined as ends up implementation dependent.

Implementations tested:
* [php_yaml](http://php.net/manual/en/book.yaml.php) will parse them all to integers
* [symfony/yaml](https://github.com/symfony/yaml) will parse 01-07 to integers and then 08 and 09 to integer 0 (raising an exception when they're both there)
* [PyYAML](https://pyyaml.org/) will parse 01-07 as integers, and then 08 and 09 to strings.

Minimum example to test parsing:
```
01: Yes
02: No
03: Yes
04: No
05: Yes
06: No
07: Yes
08: No
09: Yes
10: No
```

**Comment by JoeLametta** [comment]
Thanks for reporting this issue.
I think there are two ways to solve this: either dropping leading zeros from the track number or quoting track numbers in the logfile. What do you suggest?

**Comment by itismadness** [comment]
I'd suggest dropping the leading zero as I think that'd look more natural to end users looking at the outputted log?
