### ISSUE TITLE
On Ubuntu 18.10 cd-paranoia binary is called cdparanoia

### ISSUE THREAD

**Issue by kwach** [whipper-team/whipper#347]
I'm just trying to use whipper like this on Ubuntu 18.10:

```$ python2 -m whipper drive analyze
whipper: error: missing dependency "cd-paranoia"
```

After fixing `whipper/program/cdparanoia.py` cd-paranoia->cdparanoia it works.

**Comment by MerlijnWajer** [comment]
These are two distinct project - try to install `libcdio-paranoia2`.

**Comment by kwach** [comment]
Thanks for quick answer.
From http://manpages.ubuntu.com/manpages/artful/en/man1/cd-paranoia.1.html and  https://bugs.launchpad.net/ubuntu/+source/libcdio/+bug/1750264 I learnt that cd-paranoia is no longer available in Ubuntu 18.04 and later.

**Comment by MerlijnWajer** [comment]
@JoeLametta - should we reflect this in our README somewhere? I think we also had this with debian (as the bug link above indicates)

**Comment by JoeLametta** [comment]
> @JoeLametta - should we reflect this in our README somewhere? I think we also had this with debian (as the bug link above indicates)

Yeah, will add it to the README. More information about Debian's package issue in https://github.com/whipper-team/whipper/issues/220#issuecomment-364378192.
