### ISSUE TITLE
Doesn't eject - "eject: unable to eject" (but manual eject works)

### ISSUE THREAD

**Issue by edrozenberg** [whipper-team/whipper#355]
At the end of rips I get the following notice and the disk does not eject:

```eject: unable to eject```

But manual eject works fine:

```$ eject /dev/sr0```

My user is part of the ```cdrom``` group and I have no problems with ripping or disk access as a regular user.

My drive is a push-to-close model, Toshiba SuperMultiPA3761.

My software info, in case it's relevant:
- Slackware64 14.2+
- whipper-0.7.3
- cddb-py-1.4
- cdparanoia-III_10.2
- cdrdao-1.2.4
- libcddb-1.3.2
- libcdio-2.0.0
- libcdio-paranoia-10.2+0.94+2
- pycdio-2.0.0
- mutagen-1.42.0

**Comment by edrozenberg** [comment]
I believe the issue was temporary loss of connectivity to the drive - also caused the rip to be incomplete. Possible cause was not using both connectors on the USB Y-splitter cable. Perhaps the drive experienced a temporary loss of power/insufficient power.

Using both ends of the Y cable now, eject worked fine on a recent rip.

**Comment by jtl999** [comment]
I had a similar issue with a dodgy eSATA cable that kept causing CRC bus errors.
