### ISSUE TITLE
Rip while entering MusicBrainz data

### ISSUE THREAD

**Issue by srussel** [whipper-team/whipper#360]
When I comes across a CD that is not in MusicBrainz, I can not start the rip until I have entered all the information into MusicBrainz. It would save a bit of time if whipper could start the ripping to temporary files while I am entering the MusicBrainz data then refetch the MusicBrainz data at the end of the rip and apply it to the ripped files.

**Comment by JoeLametta** [comment]
Sorry, wouldn't it be easier to just use a music tagging/organizer software after the rip has been completed to apply the metadata?

**Comment by jtl999** [comment]
The way I see it, there should be at least some metadata for the rip for the artist/album name and log file.

**Comment by kietoparao** [comment]
I believe that's why you have the `-U` (`--unknown`) argument to continue ripping if the CD is unknown, and once the rip is finished you can apply the correct tags to it from MusicBrainz.

**Comment by JoeLametta** [comment]
No reply in more than two weeks: closed.
