### ISSUE TITLE
Drive analysis fails

### ISSUE THREAD

**Issue by NovaPhoenix** [whipper-team/whipper#361]
After running `whipper drive analyse` (both with and without drive specified) I get this error: `CRITICAL:whipper.command.drive:cannot analyze the drive: is there a CD in it?`
There is a CD in the drive and other programs are able to access it. I am able to play the CD using Clementine and other audio players. I'm using whipper 0.7.3 on Fedora 29. Here's my drive:
```
$ whipper drive list
drive: /dev/cdrom, vendor: HL-DT-ST, model: DVD+-RW GU90N   , release: A1C2
```
 Logs attached.

[Output of `WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper drive analyze`](https://github.com/whipper-team/whipper/files/2809723/whipper.log.gz)

**Comment by JoeLametta** [comment]
I've identified the issue, it will be fixed soon.
