### ISSUE TITLE
AssertionError in assert self.itable.getCDDBDiscId() in cd.py

### ISSUE THREAD

**Issue by o1t1** [whipper-team/whipper#377]
`WHIPPER_DEBUG=DEBUG WHIPPER_LOGFILE=whipper.log whipper cd rip`
on a specific disc produces [whipper.log.gz](https://github.com/whipper-team/whipper/files/2906312/whipper.log.gz) with whipper v0.7.3, cdrdao v1.2.4

same as [#72](https://github.com/whipper-team/whipper/issues/72)?

**Comment by JoeLametta** [comment]
> same as [#72](https://github.com/whipper-team/whipper/issues/72)?

Not enough details but it probably is.
