### ISSUE TITLE
cdda2wav from cdrtools instead of cdparanoia

### ISSUE THREAD

**Issue by emk2203** [whipper-team/whipper#38]
I would suggest to use [cdda2wav](http://www.cdda2wav.de/) with -paranoia switch instead of cdparanoia.

cdparanoia is not actively developed, cdda2wav is. I used abcde for ripping, which gives you the option of cdparanoia or cdda2wav, and the latter gave much better results (quicker, less error-prone).

**Comment by BoBeR182** [comment]
This will fix the Julie Roberts bug?

**Comment by MerlijnWajer** [comment]
As far as I am concerned, it is not clear if that will fix the issues that cdparanoia seems to have on specific CDs. It may be worth it also to try a bit harder to get cdparanoia developers to respond to our issues. If someone wants to try to implement a program/task wrapper for cdda2wav, with progress and error parsing, feel free to do it. Isn't there also another (lib)paranoia implementation from gnu libcdio? Maybe that also helps.

**Comment by 45054** [comment]
Does cdda2wav allow for a sample offset correction? I'm only able to find a parameter for whole sector offsets.

**Comment by JoeLametta** [comment]
> Does cdda2wav allow for a sample offset correction?

I think it doesn't.

**Comment by JoeLametta** [comment]
As we're working in the direction of #87, can I close this issue?

**Comment by Freso** [comment]
No response in over 4 months: I say close it.

**Comment by JoeLametta** [comment]
> No response in over 4 months: I say close it.

Done.

😉
