### ISSUE TITLE
Include MusicBrainz Release ID in the log file

### ISSUE THREAD

**Issue by srussel** [whipper-team/whipper#381]
It would be useful to include the MusicBrainz Release ID and lookup url in the log file similar to what currently done with the Disc ID.  I would like to be able to know which release id was used for the metadata in the case of multiple matches and be able to easily look it up in MB in case I need to correct any details.

**Comment by Freso** [comment]
Can you take a look at https://github.com/whipper-team/whipper/pull/382 and see if that looks like what you’re requesting? :)

**Comment by srussel** [comment]
Looking at the sample log output in #382, yes that is exactly what I am looking for. Thanks for the  quick patch.

**Comment by JoeLametta** [comment]
Just merged it in the develop branch. It will land in whipper's next release.
