### ISSUE TITLE
Change documentation from epydoc to reStructuredText

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#383]
Currently the code has many instances of [epydoc](http://epydoc.sourceforge.net/) annotation/syntax in e.g. docstrings. Epydoc predates [reStructuredText](http://docutils.sourceforge.net/rst.html) which has since been adopted as the (de facto, at least) "standard" for Python documentation. The last version of epydoc was on January 2008, the latest version of reST was in 2016. I'm not sure if there are any good stats for epydoc adoption, but reST at least is alive and well, even outside of Python where e.g., [the Linux kernel](https://lwn.net/Articles/692704/) and [CMake](https://cmake.org/cmake/help/v3.0/release/3.0.0.html#documentation-changes) have adopted it.

There's no real direct/immediate benefit of switching, but reST would be more likely to be familiar to new contributors and even for someone who's never experienced either, it would likely be more valuable to get familiar with reST than epydoc, as reST is used for more things. I feel like reST is also more "embedded" in the Python ecosystem as a whole, which may result in more tools etc. being at disposal for dealing with it.

So overall, I'd like to propose that we also at some point change over the documentation (e.g., docstrings) to use reST instead of epydoc. (Please indicate whether you agree or don't agree in comments or by using :+1:/:-1: reactions.)

**Comment by JoeLametta** [comment]
I support this change. I've already attempted something like this in #211 (which was reverted in #246).
It's not hard to do: it can even be scheduled for milestone 1.0 as "Stretch".

:wink:

**Comment by Freso** [comment]
Well, I consider a lot of things in the 2.0 milestone as stretch goals for 1.0. :p But I'd rather not have this as a requirement for 1.0. If we do it before 1.0, great, but it shouldn't be something that holds a 1.0 release back.

**Comment by JoeLametta** [comment]
This should have been fixed with pull requests #387 and #389.
