### ISSUE TITLE
Why is CD-Text  if found not used for naming Disk and Tracks?

### ISSUE THREAD

**Issue by bitstreamout** [whipper-team/whipper#397]
... if there is no entry on musicbrainz.org (hey there is also fddb.org) the resulting ripped data tree shows 'Unknown Artist'  as well as Nonsens in disk and track file names. 

Btw:  'whipper cd info'  shows 
```
INFO:whipper.command.cd:checking device /dev/sr0
eject: CD-ROM tray close command failed: Input/output error
INFO:whipper.command.cd:reading TOC...
CDDB disc id: f7113912
MusicBrainz disc id A59uocvYUbLE81SCouKIZ2TDuNg-
MusicBrainz lookup URL https://musicbrainz.org:80/cdtoc/attach?toc=1+18+330858+150+11388+27912+47828+66441+88747+104769+120627+145386+165286+187699+213634+228216+245080+266232+286822+301645+315377&tracks=18&id=A59uocvYUbLE81SCouKIZ2TDuNg-
Disc duration: 01:13:29.440, 18 audio tracks
WARNING:whipper.common.program:release not found: (NotFoundException(ResponseError(),),)
WARNING:whipper.common.program:continuing without metadata
Submit this disc to MusicBrainz at the above URL.

CRITICAL:whipper.command.cd:unable to retrieve disc metadata, --unknown argument not passed
```

**Comment by bitstreamout** [comment]
Hello (Auto)Bot: Steps to reproduce is simply: whipper cd rip -U    .. but meanwhile I've added a [whipper.cd.rip] section in the config file below ~/.config/whipper/ which includes the unkwon = True As well as some naming schemes

**Comment by bitstreamout** [comment]
Hmm ... the cue file shows CD-Text informations but filenames as well as the meta information in the flac files are Unknown ...
``
   comments: 5
    comment[0]: ALBUM=Unknown Disc
    comment[1]: TRACKNUMBER=1
    comment[2]: TITLE=Unknown Track
111    comment[3]: MUSICBRAINZ_DISCID=A59uocvYUbLE81SCouKIZ2TDuNg-
    comment[4]: ARTIST=Unknown Artist
``

which correspond with the cue file

``REM DISCID F7113912
REM COMMENT "whipper 0.7.3"
TITLE "One Hit Wonder Vol.14 - CD1"
FILE "0000 01. Unknown Track 1.flac" WAVE
  TRACK 01 AUDIO
    TITLE "YOLANDA BE COOL & DCUP - We No Speak Americano"
    ISRC ITA199800041
    INDEX 01 00:00:00
[...]``

(To be noted : I've owned this CD legal and I'd liek to get an exact flac version onto my NAS.)

**Comment by JoeLametta** [comment]
Hi, it's not used by default since CD-Text metadata isn't always available (it's usually low quality too). However maybe it makes sense to add an option to use it, if available, together with the `unknown` flag.

@Freso @MerlijnWajer What's your opinion about this?

**Comment by bitstreamout** [comment]
On Fri, May 03, 2019 at 02:09:28AM -0700, JoeLametta wrote:
> Hi, it's not used by default since CD-Text metadata isn't always available (it's usually low quality too). However maybe it makes sense to add an option to use it, if available, together with the `unknown` flag.
> 
> @Freso @MerlijnWajer What's your opinion about this?

Ohmmm ... maybe an option to submit this to FreeDB and/or MusicBrainz ;)

**Comment by JoeLametta** [comment]
See #425.
