### ISSUE TITLE
GUI frontend for whipper

### ISSUE THREAD

**Issue by 45054** [whipper-team/whipper#40]
Sometime after the whole migration and reorganisation process has been completed, it would probably be nice to have a GUI (although the CLI syntax is pretty straight forward). 

https://github.com/giorgiofranceschi/xaudiocopy could be used as a starting point.

Edit: There even is a GTK3 Version https://github.com/giorgiofranceschi/xaudiocopy3

**Comment by JoeLametta** [comment]
Good idea for the long term.
I won't personally work on this one (maybe it should be developed as a separate project) but anybody working on this one will get my approval.

**Comment by JoeLametta** [comment]
Feel free to reopen if new ideas / contributions arise.

**Comment by keithhanlon** [comment]
I vibe-coded this for my own use, but decided to share it on Github when I saw this thread. 
https://github.com/keithhanlon/whipper-frontend
