### ISSUE TITLE
more template options for filenames

### ISSUE THREAD

**Issue by andreas-h** [whipper-team/whipper#401]
I think it would be useful to have more options to generate the filenames of ripped files.  Especially having a DISCNUMBER would be good, as then, one could do something like `DISCNUMBER-TRACKNUMBER_andsoon.flac`.

As a bonus, having the option for `DISCNUMBER-TRACKNUMBER_andsoon.flac` in case of multi-disc releases, and `TRACKNUMBER_andsoon.flac` for single-disc releases would be great.

I know MusicBrainz Picard supports this using some advanced template logic.

Given that Picard is also Python, maybe using some code from Picard in whipper to implement this would be an option.

What do you think?  Would you accept a PR for this (i.e., using Picard code in whipper for template generation)?

**Comment by Freso** [comment]
I agree with the sentiment that it would be good to have more template options available. Can you maybe suggest a list of which ones you would like to see or find useful?

About borrowing Picard’s template system… I can almost guarantee that that won’t happen (anytime soon). Picard’s (re)naming system is way too advanced for what whipper is, at least at the current point in time. *Maybe* it’s something to consider once we have more/better unit tests, the code is cleaned up more from its morituri days, once it’s been ported to Python 3, etc., etc. Basically, the code has to be in a much better state than it is now before we even consider adding a significant amount of new logic to it.

**Comment by JoeLametta** [comment]
@andreas-h Any reply?

**Comment by JoeLametta** [comment]
@andreas-h Any reply?

**Comment by Forage** [comment]
The only one I'm missing from the list already implemented are: disc number and disc title (which is now used for the release title).
And, as already partially suggested as well, it would be great to have a way to make a distinction between single-disc and multi-disc releases.
Maybe something like only filling the disc number variable if there are more than one discs in the selected release and the use of square brackets in the template to make that part optional if a variable instead actually contains a value.

Example, if `i` would be the disc number:
`DEFAULT_TRACK_TEMPLATE` = '%A/%d/[disc %i/]%t. %n'`

Which would give you
`Dream Theater/A Change of Seasons/01. A Change of Seasons.flac`
For the first track of the single disc release `A Change of Seasons`.
And
`Dream Theater/Six Degrees of Inner Turbulence/disc 1/01. The Glass Prison.flac`
For the first track of the first disc of the two disc release `Six Degrees of Inner Turbulence`

Any change for adding more template variables would require a change to stop using single character variable names as well I think. Full names would be a lot easier to understand.

**Comment by Forage** [comment]
It looks like #476 already addresses the disc number and disc title options I'd like to see. The last option I'd like to add to that list is the discid. Personally I'm only interested in the MusicBrainz discid, but for completeness the CDDB discid in addition to that wouldn't hurt either.

I suppose the optional part with square brackets and renaming the options to full names should be treated as two separate issues.
