### ISSUE TITLE
Replace spaces in artist/album/track name with underscore or other custom character

### ISSUE THREAD

**Issue by robguinness** [whipper-team/whipper#405]
Hi, I just discovered whipper today. I didn't find an option to replace spaces in the artist/album/track data that comes from MusicBrainz with some other character (e.g. _) for use in directory/filenames. I was thinking about making a PR to add this as an option. Would that be something others are interested in?

**Comment by walterav1984** [comment]
I'm interested, maybe combine it with an option for limiting even more simple filesystem unfriendly  characters or filename lengths.

**Comment by smithbone** [comment]
+1 for this feature as well.

**Comment by JoeLametta** [comment]
Hi @robguinness, sorry for the late reply. I think that what you're asking is already being worked on (in #324). A similar discussion already happened in #313 so I'll close this issue in favour of #313 (if you think this is wrong, feel free to reopen the issue).

Cheers,
Joe
