### ISSUE TITLE
exception while reading CD

### ISSUE THREAD

**Issue by smithbone** [whipper-team/whipper#413]
I get this when I try to rip one of my CDs.

rsmith@engine37:~/Music/riptest$ WHIPPER_DEBUG=debug whipper --eject=always cd rip
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:looking at section u'drive:ATAPI%20%20%20%3ADVD%20A%20%20DH16ABSH%20%3AYA12'
DEBUG:whipper.common.config:vendor: 'ATAPI   ' versus 'ATAPI'
DEBUG:whipper.common.config:model: 'DVD A  DH16ABSH ' versus 'DVD A  DH16ABSH'
DEBUG:whipper.common.config:release: 'YA12' versus 'YA12'
INFO:whipper.command.cd:using configured read offset 6
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
DEBUG:whipper.common.config:loaded 2 sections from config file
INFO:whipper.command.cd:checking device /dev/sr0
DEBUG:whipper.program.utils:loading (eject -t) device /dev/sr0
DEBUG:whipper.program.utils:possibly unmount real path '/dev/sr0'
DEBUG:whipper.extern.task.task:run task <whipper.program.cdrdao.ReadTOCTask object at 0x7f3f3fb87f50>
DEBUG:whipper.extern.task.task:Adding listener <whipper.common.task.SyncRunner object at 0x7f3f3fb87e90>
DEBUG:whipper.extern.task.task:run loop
DEBUG:whipper.extern.task.task:start task <whipper.program.cdrdao.ReadTOCTask object at 0x7f3f3fb87f50>
DEBUG:whipper.extern.task.task:starting
DEBUG:whipper.extern.task.task:notifying progress: 0.0 on 'Reading TOC'
DEBUG:whipper.extern.task.task:notifying progress: 1.0 on 'Reading TOC'
DEBUG:whipper.image.table:set logName
DEBUG:whipper.extern.task.task:exception when calling scheduled callable <bound method ReadTOCTask._read of <whipper.program.cdrdao.ReadTOCTask object at 0x7f3f3fb87f50>>
DEBUG:whipper.extern.task.task:set exception, IOError(2, 'No such file or directory'), "exception IOError at /usr/lib/python2.7/codecs.py:898: open(): [Errno 2] No such file or directory: u'/tmp/tmpvohYIz.cdrdao.read-toc.whipper.task'"
DEBUG:whipper.extern.task.task:stopped task <whipper.program.cdrdao.ReadTOCTask object at 0x7f3f3fb87f50>
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/extern/task/task.py", line 519, in c
    callable_task(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/program/cdrdao.py", line 112, in _read
    self._done()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/program/cdrdao.py", line 150, in _done
    self.toc.parse()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/image/toc.py", line 192, in parse
    handle = codecs.open(self._path, "r", "utf-8")
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/tmp/tmpvohYIz.cdrdao.read-toc.whipper.task'
DEBUG:whipper.extern.task.task:done running task <whipper.program.cdrdao.ReadTOCTask object at 0x7f3f3fb87f50>
DEBUG:whipper.extern.task.task:raising TaskException for "exception IOError at /usr/lib/python2.7/codecs.py:898: open(): [Errno 2] No such file or directory: u'/tmp/tmpvohYIz.cdrdao.read-toc.whipper.task'", 'Traceback (most recent call last):\n  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/extern/task/task.py", line 519, in c\n    callable_task(*args, **kwargs)\n  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/program/cdrdao.py", line 112, in _read\n    self._done()\n  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/program/cdrdao.py", line 150, in _done\n    self.toc.parse()\n  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/image/toc.py", line 192, in parse\n    handle = codecs.open(self._path, "r", "utf-8")\n  File "/usr/lib/python2.7/codecs.py", line 898, in open\n    file = __builtin__.open(filename, mode, buffering)\nIOError: [Errno 2] No such file or directory: u\'/tmp/tmpvohYIz.cdrdao.read-toc.whipper.task\'\n'
CRITICAL:whipper.command.main:exception IOError at /usr/lib/python2.7/codecs.py:898: open(): [Errno 2] No such file or directory: u'/tmp/tmpvohYIz.cdrdao.read-toc.whipper.task'
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/extern/task/task.py", line 519, in c
    callable_task(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/program/cdrdao.py", line 112, in _read
    self._done()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/program/cdrdao.py", line 150, in _done
    self.toc.parse()
  File "/usr/local/lib/python2.7/dist-packages/whipper-0.7.4.dev77+g635113b.d20190901-py2.7.egg/whipper/image/toc.py", line 192, in parse
    handle = codecs.open(self._path, "r", "utf-8")
  File "/usr/lib/python2.7/codecs.py", line 898, in open
    file = __builtin__.open(filename, mode, buffering)
IOError: [Errno 2] No such file or directory: u'/tmp/tmpvohYIz.cdrdao.read-toc.whipper.task'

**Comment by JoeLametta** [comment]
Please provide more details or I won't be able to investigate on this issue. (I'm going to close it in a week if I get no reply)

**Comment by whoopsmith** [comment]
I don't have more info than the debug in the ticket.  I don't remember what CD that was.  Sorry.

**Comment by whoopsmith** [comment]
If that's not enough you can close.  If I find another one I can make a new ticket.

**Comment by Freso** [comment]
At a glance this looks like potentially a race condition (a directory either didn’t get created in time or got purged before being done with) or a file system issue (the directory couldn’t get created).

Some of the changes included with the Python 3 port dealt with at least the race conditions (using `with open(): …` pattern), so chances are whatever cause this has been fixed. I’ll close this. Feel free to re-open or make a new issue if you encounter this again.
