### ISSUE TITLE
Wrong version number in release

### ISSUE THREAD

**Issue by ArchangeGabriel** [whipper-team/whipper#422]
(Follow-up of #420)

Recent changes induced this at building time from Github release tarball:
```
Traceback (most recent call last):
  File "setup.py", line 28, in <module>
    'scripts/accuraterip-checksum',
  File "/usr/lib/python2.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
    _setup_distribution = dist = klass(attrs)
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 446, in __init__
    k: v for k, v in attrs.items()
  File "/usr/lib/python2.7/distutils/dist.py", line 287, in __init__
    self.finalize_options()
  File "/usr/lib/python2.7/site-packages/setuptools/dist.py", line 734, in finalize_options
    ep.load()(self, ep.name, value)
  File "/build/whipper/src/whipper-0.8.0/.eggs/setuptools_scm-3.3.3-py2.7.egg/setuptools_scm/integration.py", line 17, in version_keyword
    dist.metadata.version = get_version(**value)
  File "/build/whipper/src/whipper-0.8.0/.eggs/setuptools_scm-3.3.3-py2.7.egg/setuptools_scm/__init__.py", line 150, in get_version
    parsed_version = _do_parse(config)
  File "/build/whipper/src/whipper-0.8.0/.eggs/setuptools_scm-3.3.3-py2.7.egg/setuptools_scm/__init__.py", line 113, in _do_parse
    "use git+https://github.com/user/proj.git#egg=proj" % config.absolute_root
LookupError: setuptools-scm was unable to detect version for '/build/whipper/src/whipper-0.8.0'.

Make sure you're either building from a fully intact git repository or PyPI tarballs. Most other sources (such as GitHub's tarballs, a git checkout without the .git folder) don't contain the necessary metadata and will not work.
```
But building from a git clone of the 0.8.0 tag ends up with:
```
$ whipper --version
whipper 0.8.1.dev0+g4238e71.d20191030
```
I did not look where the version number was computed, but currently this is not working as I would expect.

**Comment by ArchangeGabriel** [comment]
Related to #370.

**Comment by Freso** [comment]
We don’t have any `setup.cfg` changing how `setuptools_scm` calculate release versions, so we should be following the pattern of https://github.com/pypa/setuptools_scm/#default-versioning-scheme

Can you paste the output of `git describe --long --tags`?

**Comment by ArchangeGabriel** [comment]
`v0.8.0-0-g4238e71` in both `build`, `check` and `package`.
However `python2 setup.py --version` is returning `0.8.0` in the first two, but `0.8.1.dev0+g4238e71.d20191031` in the third one because… I’m patching locally for #420 (and thus the tree is not clean anymore at `package` time).
Checking out the file afterwards works. So how are people expected to eventually patch locally but still get the right version number?

**Comment by Freso** [comment]
I mean, if you patch the file locally, then that *is* the correct version number you’re getting.

**Comment by ArchangeGabriel** [comment]
Not really… It just says the tree wasn’t clean at build time on the given date. Building another time will have a different version number, but that does not makes sense. And any change will have this same version number, but could have very different content. So this version number does not make any sense.

Anyway for this time I’ve built whipper bypassing this since we only modify a test during check.

**Comment by Freso** [comment]
You could apply the patch as a git commit, that way you will get a `.dev1+g…` instead.

**Comment by jpalus** [comment]
Not that I think anyone cares, but being whipper maintainer in my distribution of choice, it's enough of a reason to stop updating whipper to new versions. Requiring git checkout just to get a proper release version is an overkill.

**Comment by adrienbeau** [comment]
According to the message above (*Make sure you're either building from a fully intact git repository or PyPI tarballs*), you should be able to use the PyPI tarballs rather than git checkout. Does that not work for you?

**Comment by jpalus** [comment]
This is a generic setuptools-scm error message. There are no PyPI tarballs for whipper or at least none I'm aware of.
