### ISSUE TITLE
Provide option to not use disambiguation in title

### ISSUE THREAD

**Issue by srussel** [whipper-team/whipper#440]
Currently the disc title used in the template %d and the log file name contains the disambiguation. For example this [release](https://musicbrainz.org/release/9dbc23e7-aeeb-4e1f-bfa0-19b07f74a489) whipper uses the title "The Best of the Art of Noise (pink cover)". I would prefer to just use "The Best of the Art of Noise" without the disambiguation as it just adds unnecessary clutter to the title. And this example is one of the shorter ones. In some cases the disambiguation can be lengthy.

Maybe there could be an option to disable this or provide a different template variable for the plain title.

**Comment by the-confessor** [comment]
I would like to see this too. 

The title used by whipper right now is a combination of the release title, the disambiguation, the medium title, and the disc number. Ideally I would like to see each of these three available as separate templates.

For example, I was ripping [this CD](https://musicbrainz.org/release/f01fd97f-8b36-40d6-bff4-5119dd940acc) and it gave me the following metadata:

```
CDDB disc id: 34121d16
MusicBrainz disc id G3m76xuCQf58XB7VVkZX_B95Bwo-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+22+347942+150+6477+30331+39838+46238+69068+83481+92660+101810+106472+126641+140022+165499+177193+200393+219690+237146+253143+266852+279259+292952+310269&tracks=22&id=G3m76xuCQf58XB7VVkZX_B95Bwo-
Disc duration: 01:17:17.226, 22 audio tracks

Matching releases:

Artist  : Camille
Title   : ilo lympia (CD + BR) (Disc 1 of 2): le cd
Duration: 01:17:16.460
URL     : https://musicbrainz.org/release/f01fd97f-8b36-40d6-bff4-5119dd940acc
Release : f01fd97f-8b36-40d6-bff4-5119dd940acc
Type    : Live
Barcode : 5099990343698
Cat no  : 5099990343629
```

Ultimately what I'd like to see is more like the following, where the release/medium/disambiguation/disc values are available as separate templates.

```
Artist  : Camille
Title   : ilo lympia (CD + BR) (Disc 1 of 2): le cd
Release : ilo lympia
Medium  : le cd
Disambiguation: CD + BR
Disc    : 1 of 2
Duration: 01:17:16.460
URL     : https://musicbrainz.org/release/f01fd97f-8b36-40d6-bff4-5119dd940acc
Release : f01fd97f-8b36-40d6-bff4-5119dd940acc
Type    : Live
Barcode : 5099990343698
Cat no  : 5099990343629
```
