### ISSUE TITLE
output directory isn't read

### ISSUE THREAD

**Issue by kroeckx** [whipper-team/whipper#441]
With a current git develop snapshot, it doesn't seem to take the output_directory from the config file into account.

I'm running:
python3 -m whipper cd rip

~/.config/whipper/whipper.conf contains this section:
[whipper.cd.rip]
unknown = True
output_directory = /kurt/kurt/music-rip/

But the output is in ./album/

**Comment by myuhe** [comment]
Same issue occurred.
run 
 whipper cd rip --output-directory='/home/foo/music/'

then
 output directory is in root directory.

environment:
ArchLinux
Python 3.8.1
whipper0.9.0

**Comment by ABCbum** [comment]
Hi, i don't know if this would help but how about trying specifying the current directory ? Maybe something like `./home/foo/music` or `~/kurt/kurt/music-rip/` (not sure about the latter one but yeah).

**Comment by JoeLametta** [comment]
I think this bug isn't present anymore in whipper's develop branch codebase.
