### ISSUE TITLE
Don't include full file path in log files

### ISSUE THREAD

**Issue by the-confessor** [whipper-team/whipper#445]
The default log file format includes the full file path to a ripped file, e.g.

```
Tracks:
  1:
    Filename: /media/music/Oasis - Stop the Clocks EP/Oasis - Stop the Clocks EP - 01 - Acquiesce.flac
    Peak level: 0.988617
    Pre-emphasis:
```

The full path to the file is really not relevant, especially given that the log file is contained in the same folder as the files.

I know that logger plugins are available but that seems like overkill for this case. 

Suggestion is to just include the basename of the file:

```
Tracks:
  1:
    Filename: Oasis - Stop the Clocks EP - 01 - Acquiesce.flac
    Peak level: 0.988617
    Pre-emphasis:
```

**Comment by JoeLametta** [comment]
Hi, If you don't want to have the full path included in the log have you tried using the following option when ripping?

`-W` / `--working-directory`: _working directory; whipper will change to this directory and files will be created relative to it when not absolute_.

Example:

```
whipper cd rip --working-directory=/media/music/
```

**Comment by the-confessor** [comment]
Interesting thought - I just tested with the below command and found the full file path is still captured in the log.

```
whipper cd rip --output-directory /tmp --working-directory /tmp
```

Output snippet:

```
Tracks:
  1:
    Filename: /tmp/Oasis - Stop the Clocks EP/Oasis - Stop the Clocks EP - 01 - Acquiesce.flac
    Peak level: 0.988617
```

**Comment by JoeLametta** [comment]
@the-confessor Have you tried specifying just the `--working-directory` option and see if it works that way? In case it still doesn't work I think we've found a regression...

**Comment by the-confessor** [comment]
I did try that also, though I didn't capture it at the time. Result was the same.

**Comment by JoeLametta** [comment]
Hi, don't know if something has changed in the meantime but I've just tested this and it seems to work as expected:
- If neither `-O OUTPUT_DIRECTORY, --output-directory OUTPUT_DIRECTORY` nor `-W WORKING_DIRECTORY, --working-directory WORKING_DIRECTORY` are specified, then the relative path to whipper's working directory is included in the log (following the structure defined in the templates). The rip files/folder are placed, according to the templates, under whipper's working directory.
- If `-O OUTPUT_DIRECTORY, --output-directory OUTPUT_DIRECTORY` nor `-W WORKING_DIRECTORY, --working-directory WORKING_DIRECTORY` is specified, then the full path is included in the log (following the structure defined in the templates). The rip files/folder are placed, according to the templates, under the given path.
- If `-W WORKING_DIRECTORY, --working-directory WORKING_DIRECTORY` is specified, then the relative path to the given path is included in the log (following the structure defined in the templates). The rip files/folder are placed, according to the templates, under the given path.
