### ISSUE TITLE
Display release country in matching releases

### ISSUE THREAD

**Issue by the-confessor** [whipper-team/whipper#451]
When I use whipper and there are multiple matching releases I like it to prompt me to confirm which one to use.

I usually find myself opening each musicbrainz URL just to look at the country for each of them, and that is how I choose.

I could avoid having to do this in most cases if the country was included in the ouput shown to me by whipper. Is it possible to add?

**Comment by ABCbum** [comment]
I think this one is some what similar to -> #167  right ?

**Comment by the-confessor** [comment]
Correct - my statement would have been better said "I am using the --prompt option so I can select the disc when there is more than one match."

#167 sounds like some enhancements related to the interactivity; I am happy with the current controls for interactivity, I would just like to see the country field presented to me when there are multiple matches.

e.g. this is what I saw for a CD I recently started to rip:

```
MusicBrainz disc id TW8p_wRBO1mXLKCI_H2HX873Qtk-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+10+187755+150+19597+34725+53272+72175+86125+102867+119312+138572+159210&tracks=10&id=TW8p_wRBO1mXLKCI_H2HX873Qtk-
Disc duration: 00:41:41.400, 10 audio tracks

Matching releases:

Artist  : Tilly and the Wall
Title   : Bottoms of Barrels
Duration: 00:41:52.000
URL     : https://musicbrainz.org/release/f4e74e9e-e58a-4e6e-ad94-d9db0de7e510
Release : f4e74e9e-e58a-4e6e-ad94-d9db0de7e510
Type    : Album
Cat no  : TL 09

Artist  : Tilly and the Wall
Title   : Bottoms of Barrels
Duration: 00:41:52.000
URL     : https://musicbrainz.org/release/6e515011-8e1e-3042-994d-9fdf50923fc1
Release : 6e515011-8e1e-3042-994d-9fdf50923fc1
Type    : Album

Please select a release [f4e74e9e-e58a-4e6e-ad94-d9db0de7e510]: 
```

This is what I would like to see:

```
MusicBrainz disc id TW8p_wRBO1mXLKCI_H2HX873Qtk-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+10+187755+150+19597+34725+53272+72175+86125+102867+119312+138572+159210&tracks=10&id=TW8p_wRBO1mXLKCI_H2HX873Qtk-
Disc duration: 00:41:41.400, 10 audio tracks

Matching releases:

Artist  : Tilly and the Wall
Title   : Bottoms of Barrels
Duration: 00:41:52.000
URL     : https://musicbrainz.org/release/f4e74e9e-e58a-4e6e-ad94-d9db0de7e510
Release : f4e74e9e-e58a-4e6e-ad94-d9db0de7e510
Type    : Album
Country  : US
Cat no  : TL 09

Artist  : Tilly and the Wall
Title   : Bottoms of Barrels
Duration: 00:41:52.000
URL     : https://musicbrainz.org/release/6e515011-8e1e-3042-994d-9fdf50923fc1
Release : 6e515011-8e1e-3042-994d-9fdf50923fc1
Type    : Album
Country  : Australia

Please select a release [f4e74e9e-e58a-4e6e-ad94-d9db0de7e510]: 
```

**Comment by ABCbum** [comment]
Ahh i get what you mean now. If that's the case how about trying to use the `--country` flag (i guess you did so let me check if the code is doing what you are suggesting).( ╹▽╹ )

**Comment by the-confessor** [comment]
It's slightly different. The --country flag will filter that matches by country. I would like to show matches from all countries, but include the country information in the whipper output. 

Use of the --country flag would require me to think about it before I put the CD in. Including country information in the output would mean I don't need to think about it unless there happens to be multiple matches.

**Comment by ABCbum** [comment]
Yeah you are right. Now it depends on what others think about this feature (I think it should be fine). Thanks for your suggestion. What do you guys think, @JoeLametta , @Freso , @MerlijnWajer ?

**Comment by JoeLametta** [comment]
Isn't this related to #166 too?

**Comment by JoeLametta** [comment]
@the-confessor Hi, i've added the feature you've requested in commit 85ccd29f51e490486dc2a576e3593a231df508e4 (branch `feature/isse-451-display-country`). I haven't tested it so, if you can, please try it and let me know if it works as expected.

Cheers,
Joe

**Comment by JoeLametta** [comment]
@the-confessor My bad: I made a mistake. The correct commit to test is 498bdd887b2d41320f677963af81bdfff02767e8.

**Comment by JoeLametta** [comment]
Related to #380.

**Comment by the-confessor** [comment]
I applied  as a patch and it seems to do what I was expecting.

Incidentally, the first two CDs I tested with revealed a release can have multiple countries. Examples follow. Ideally in such cases it would list all the countries.

https://musicbrainz.org/release/aef7bf54-2081-4151-96e8-07b612704878
https://musicbrainz.org/release/4c55906c-349b-362d-922e-956762912b42

**Comment by JoeLametta** [comment]
> I applied as a patch and it seems to do what I was expecting.

Good.

> Incidentally, the first two CDs I tested with revealed a release can have multiple countries.

@the-confessor I've just pushed a new commit (af74f3184223f3dc98c69b214f39db01d6c45d80) which should make whipper report all available countries (if available). I haven't tested it so, if you can, please try it and let me know if it works as expected.

Cheers,
Joe

**Comment by the-confessor** [comment]
I applied 6fab8e1 + af74f31 as a patch and confirm it works, it shows me all countries.
