### ISSUE TITLE
Build/Install Whipper

### ISSUE THREAD

**Issue by trleith** [whipper-team/whipper#452]
This is a documentation issue.

on the page https://github.com/whipper-team/whipper/blob/develop/README.md

1) If you have a 32-bit machine, the prebuilt Docker package won't work, you have to build it yourself. This should be mentioned.
2) There is a missing dot at the end of the line docker build -t whipperteam/whipper . <--- the dot is missing

**Comment by JoeLametta** [comment]
I've just fixed the reported issues in commit 553a6de88fb93de4c4e3fc663f4403e2a0462b7b.

Cheers,
Joe

**Comment by trleith** [comment]
Perfect -- thanks for all your help on Wednesday -- whipper is running happily on my fifteen year old computer.
