### ISSUE TITLE
Intermittent failure while checking device

### ISSUE THREAD

**Issue by the-confessor** [whipper-team/whipper#462]
Occasionally I hit an error like the following with whipper. Usually opening and closing CD drive resolves the issue. In one particular case I had to repeat that 4-5 times before the error went away.

Has anyone seen this before, know the cause, or have suggestions to help me identify the root cause?

```
### starting rip process with whipper
INFO:whipper.command.cd:using configured read offset 667
INFO:whipper.command.cd:checking device /dev/sr0
WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Input/output error')
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/whipper/extern/task/task.py", line 518, in c
    callable_task(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 111, in _read
    self._done()
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 149, in _done
    self.toc.parse()
  File "/usr/lib64/python3.6/site-packages/whipper/image/toc.py", line 191, in parse
    with open(self._path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgbvzifxl.cdrdao.read-toc.whipper.task'
CRITICAL:whipper.command.main:exception FileNotFoundError at /usr/lib64/python3.6/site-packages/whipper/image/toc.py:191: parse(): [Errno 2] No such file or directory: '/tmp/tmpgbvzifxl.cdrdao.read-toc.whipper.task'
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/whipper/extern/task/task.py", line 518, in c
    callable_task(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 111, in _read
    self._done()
  File "/usr/lib64/python3.6/site-packages/whipper/program/cdrdao.py", line 149, in _done
    self.toc.parse()
  File "/usr/lib64/python3.6/site-packages/whipper/image/toc.py", line 191, in parse
    with open(self._path) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmpgbvzifxl.cdrdao.read-toc.whipper.task'
```

**Comment by epeeist** [comment]
I am getting the same error, it appears to have something to do with opening a file in the /tmp directory. 

Whipper works for a while and then stops working with the above error (I get exactly the same error at the same place though with Python 3.7).

The /tmp directory is not full and I am able to create files in it. If I reboot the system whipper starts working again, for a while at least.

For the record I am using OpenSuse Tumbleweed and a USB attached DVD drive.

**Comment by the-confessor** [comment]
I don't know if it is related, but the last two discs I ran into this problem with happened to be singles/EPs, where the audio is all burned in near the center of the CD. One of them even has clear plastic instead of the usual reflective material on the outer edge of the CD that wasn't needed for audio.

**Comment by epeeist** [comment]
> ### starting rip process with whipper
> INFO:whipper.command.cd:using configured read offset 667
> INFO:whipper.command.cd:checking device /dev/sr0
> WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Input/output error')

One thing I have noticed is that if the CD is mounted (OpenSuse auto-mounts CDs) and the program fails to unmount it then I get the same error as you.

It looks as though it might be that the program is failing due to a previous error, in your case the failed eject, in my case the failed unmount.

**Comment by the-confessor** [comment]
I run into this problem fairly often with CD singles - sometimes an eject and re-try works around it, other times it continues to fail reliably. I will continue to troubleshoot and see if I can figure it out.

**Comment by the-confessor** [comment]
Your comment about mounting led me to another clue. My system is not even recognizing that a CD is in the drive. Normally when putting an audio CD in my drive I see the drive appear in Nautilus, labeled 'audio cd', and I can browse to it and see a file for each audio track. For these particular CDs where I am having this problem, I do not see that. It is as if it thinks no CD is in the drive at all.

So it may not be a whipper problem, although I wonder if whipper could handle the situation better.

Interestingly enough whipper fails with a different error if I try to rip with no CD in the drive.

**Comment by the-confessor** [comment]
I am going to close this issue, it is not a whipper problem. It is likely a problem with my CD drive - a Pioneer BDR-207MBK.

Related: I learned the name of the kind of CDs that give me the most problems - a "minimax CD" is a standard sized 5" CD, where the inner 3" is a readable CD and the rest is plastic. In my cases, it is always clear plastic. 

Anyway, my CD ROM drive has trouble calibrating with minimax CDs, and occasionally with regular CD singles. It's not just observable in whipper, but I can't use any software to read these. Even the eject command terminates with an I/O error:

```
$ eject -t -v
eject: using default device `/dev/sr0'
eject: device name is `/dev/sr0'
eject: /dev/sr0: not mounted
eject: /dev/sr0: is whole-disk device
eject: /dev/sr0: closing tray
eject: CD-ROM tray close command failed: Input/output error
```

It's likely a firmware issue. Pioneer Electronics's support does not seem interested in helping me solve the problem. It took several emails back and forth to even explain to them what a minimax CD is and how it is different from a mini CD. They said they would have their engineers in Japan investigate but I doubt they will. (Sigh.)
