### ISSUE TITLE
discid.disc.TOCError: Illegal track limits

### ISSUE THREAD

**Issue by h1nk** [whipper-team/whipper#463]
I'm getting this error/stack-trace for a particular disc I've been trying to rip:

```
$ docker run --rm -it --device=/dev/sr0 -v ~/.config/whipper/:/home/worker/.config/whipper/ -v ~/output/:/output/ whipper cd rip --cover-art complete
WARNING:whipper.command.main:set_hostname() takes 1 positional argument but 2 were given
INFO:whipper.command.cd:using configured read offset 6
INFO:whipper.command.cd:checking device /dev/sr0
WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1' (b'eject: CD-ROM tray close command failed: Input/output error')
CDDB disc id: 02d41001
Traceback (most recent call last):
  File "/usr/local/bin/whipper", line 11, in <module>
    load_entry_point('whipper==0.9.1.dev50+g9e63915.d20200207', 'console_scripts', 'whipper')()
  File "/usr/local/lib/python3.7/dist-packages/whipper/command/main.py", line 49, in main
    ret = cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper/command/basecommand.py", line 139, in do
    return self.cmd.do()
  File "/usr/local/lib/python3.7/dist-packages/whipper/command/cd.py", line 104, in do
    self.mbdiscid = self.ittoc.getMusicBrainzDiscId()
  File "/usr/local/lib/python3.7/dist-packages/whipper/image/table.py", line 348, in getMusicBrainzDiscId
    disc = put(values[0], values[1], values[2], values[3:])
  File "/usr/local/lib/python3.7/dist-packages/discid/disc.py", line 76, in put
    disc.put(first, last, disc_sectors, track_offsets)
  File "/usr/local/lib/python3.7/dist-packages/discid/disc.py", line 176, in put
    raise TOCError(self._get_error_msg())
discid.disc.TOCError: Illegal track limits
```

**Comment by ABCbum** [comment]
Hi @h1nk , this is happening because of the following if condition with `first = 1` and `last` is always number of audio tracks (https://github.com/metabrainz/libdiscid/blob/a599f3cb9ef6201fd1a2a0822e13de4a678f4a3c/src/disc.c#L192) . But this is really weird since there aren't many discs with over 99 audio tracks and this way of determining `first` and `last` is the same with the old code. Help please!

**Comment by h1nk** [comment]
I'm not sure what more information I can provide really. I know that the CD certainly did not have more than 99 audio tracks. I can't recall the exact disc that had this issue, but I will try to find it again and report more information. All I know is that it was in near-mint condition, so I doubt it was a defect in the CD.

**Comment by JoeLametta** [comment]
Hi, unfortunately you haven't provided enough information to investigate this issue: which CD causes this? Could you try ripping it again in whipper as explained [here](https://github.com/whipper-team/whipper#bug-reports--feature-requests).
Could you also run the following commands on the same device (same CD), then post the content of the generated files (`cdrdao_disk-info.log`, `cdrdao_read-toc_fast.log`, `cdrdao_read-toc_slow.log`, `cdrdao_fast.toc` and `cdrdao_slow.toc`)?

```bash
sudo umount /dev/sr0
cdrdao disk-info --device /dev/sr0 > cdrdao_disk-info.log 2>&1
cdrdao read-toc --device /dev/sr0 --fast-toc cdrdao_fast.toc > cdrdao_read-toc_fast.log 2>&1
cdrdao read-toc --device /dev/sr0 cdrdao_slow.toc > cdrdao_read-toc_slow.log 2>&1
```

I've also tried searching for the CDDB Disc ID on FreeDB but no results are returned...

**Comment by h1nk** [comment]
Looks like this one was a big 'ol (really really stupid) user error. Turns out disc 1 of the 2 part jewel case was a DVD and not an audio CD, sorry for wasting your time. 😅

**Comment by ABCbum** [comment]
\o/ yayy no problem.
