### ISSUE TITLE
cover_art configuration directive

### ISSUE THREAD

**Issue by h1nk** [whipper-team/whipper#465]
It seems that there's no such `cover_art` configuration directive for the `[whipper.cd.rip]` section?

I've tried the following in my user configuration file, but no album art images are produced:
```ini
[whipper.cd.rip]
cover_art = complete
```

**Comment by ABCbum** [comment]
Hi, could you provide a little bit more metadata about the disc ? Since it is possible that your disc doesn't have a cover art on Cover Art Archive.

**Comment by JoeLametta** [comment]
Thanks for reporting this issue. This happens because of an inconsistent naming: the config file should understand an option named `fetch_cover_art`.
Fixed this (adopt consistent naming, config should understand `cover_art`) in commit 6fd7a782221210d0180be7e3cd8aff44f01aa058.
