### ISSUE TITLE
Filename / Tags 

### ISSUE THREAD

**Issue by a491765** [whipper-team/whipper#466]
Hi,

Seems not to be an issue but not sure if its a resquest too...

I'm happy using  whipper with snap under Debian Buster.
Amazing job done here Thanks for that !

1 / I would like to be able to choose the naming format of ripped files :
Today : Tracknumber - Artist - Title.flac
My wish : Tracknumber - Title.flac

The problem is that renaming after make .cue / .log / .m3u useless or fastidious job to rename manually them.

2/ Choose the tag added to the ripped file because i don't want all to be add (like ID of musicbrainz are useless in my case after ripping...) but some wanted to be add (DISCNUMBER, TOTALTRACK, TOTALDISC...) without using Picard.

It would be ok to make those modifications manually if someone can tell me the way to go

Thanks.

**Comment by a491765** [comment]
Ok i have found how to did it with command line :

Using r

`whipper cd rip -L whipper -W /home/a/Musique --track-template " %t. %n (%s)"`

But Now flac are in /Musique and .cue .log. m3u are in /Musique/Album/the_album_name

**Comment by Freso** [comment]
> Choose the tag added to the ripped file

FWIW, I’m strongly against this. I’d rather save less tags to the files than go down the slope of having to manage which tags to let whipper save. And I 100% think the MusicBrainz (and other) identifiers should remain, as these allow [other applications](https://musicbrainz.org/doc/MusicBrainz_Enabled_Applications) to easily pull in additional information about the tracks, without the uncertainty of text string search-based lookups. If people want more or less tags than what whipper provides, they can do that with other tools after the rip.

**Comment by a491765** [comment]
Yes it's not a big deal, was just a way to save time in automation and forget Picard ;)

**Comment by Freso** [comment]
There are several taggers other than Picard that use MusicBrainz IDs as part of their workflow. I don’t generally use Picard to tag my files (I use [beets](http://beets.io/)). When I said "other applications", I linked a list that has a bunch of applications in it. Even if you don’t do additional tagging outside of whipper, media centers such as Kodi or Plex are able to use the embedded MusicBrainz IDs to recognise the tracks and look up additional information.

**Comment by Freso** [comment]
> @Freso do you know how i can solve my main problem of ripping directory ?

Not really, partially because I don’t fully understand 1) what you’re doing, 2) what you’re getting, 3) what you’re expecting.

**Comment by a491765** [comment]
> > @Freso do you know how i can solve my main problem of ripping directory ?
> 
> Not really, partially because I don’t fully understand 1) what you’re doing, 2) what you’re getting, 3) what you’re expecting.

1) I try to ripp CD using the good command and sub command to have the good result

3) I would like to rip a cd which is rip in /home/Musique/thealbumname
Where flac are reaming 01. Title.flac
Where .cue .log .m3u don't show complete path (/home/Music...) of the track but the root of thealbum folder.

I use `whipper cd rip -W /home/a/Musique --track-template "%t. %n (%s)`

But the result isn't good :

Files are ripped in /home/Musique and show the good track temple (all this is good)
But the .m3u, the .log and the .cue are ripped in /home/Musique/album/thealbumname

So i have to move .m3u .log .cue but then they don't work anymore (path in is wrong)

Hope i am a bit clearer

**Comment by JoeLametta** [comment]
@a491765 I agree with @Freso about the tags.

Regarding to the template issue keep in mind that whipper has two template options: `--track-template` and `--disc-template`. Explanation:

> Tracks are named according to the track template, filling in the variables and adding the file extension. Variables exclusive to the track template are:
>  - %t: track number
>  - %a: track artist
>  - %n: track title
>  - %s: track sort name
> 
> Disc files (.cue, .log, .m3u) are named according to the disc template, filling in the variables and adding the file extension. Variables for both disc and track template are:
>  - %A: release artist
>  - %S: release sort name
>  - %d: disc title
>  - %y: release year
>  - %r: release type, lowercase
>  - %R: release type, normal case
>  - %x: audio extension, lowercase
>  - %X: audio extension, uppercase
