### ISSUE TITLE
Trying to figure out the naming scheme template

### ISSUE THREAD

**Issue by peaveyman** [whipper-team/whipper#468]
I have been trying to figure out the name scheme template but I am at a loss. I want the output to be like this: Artist - Albumtitle/Albumtitle - Tracknumber - Songtitle

I want to put the template in the config file so all I have to use is whipper cd rip

Any help would be appreciated.

**Comment by JoeLametta** [comment]
Hi, in whipper's configuration file (in the section named `[whipper.cd.rip]`) set the `track_template` and `disc_template` options to the following value (if these lines are absent, just copy and paste them):

```ini
track_template = %%A - %%d/%%d - %%t - %%n
disc_template = %%A - %%d/%%d
```

**Comment by JoeLametta** [comment]
Any update on this?
