### ISSUE TITLE
Musicbrainz lookup fails for multiple CD rip

### ISSUE THREAD

**Issue by epeeist** [whipper-team/whipper#477]
I have Monteverdi's Vespro della beata Vergine which consists of 2 CDs 

Whipper finds the first CD on MusicBrainz (https://musicbrainz.org/release/1757bdb7-0d21-4ee2-b5f4-076e18ab8b0d) but reports fails to find the tracks on the second CD even though they appear to be in the MusicBrainz CD

The error messages are:

CDDB disc id: b20d160f
MusicBrainz disc id .RmqVjEYp99iqmKU_dpg4v.tDjg-
MusicBrainz lookup URL https://musicbrainz.org/cdtoc/attach?toc=1+15+251445+182+3057+24700+39510+43012+79645+82010+84510+162437+191270+196325+198157+220170+243760+245460&tracks=15&id=.RmqVjEYp99iqmKU_dpg4v.tDjg-
Disc duration: 00:55:50.173, 15 audio tracks
WARNING:whipper.common.program:continuing without metadata
Submit this disc to MusicBrainz at the above URL.

INFO:whipper.command.cd:FreeDB identifies disc as ['Claudio Monteverdi / Vespro della Beata Vergine - Parrot - 2']
CRITICAL:whipper.command.cd:unable to retrieve disc metadata, --unknown argument not passed

**Comment by Freso** [comment]
Your disc seems to have 15 tracks (based on the "add Disc ID" URL), while the one you’re linking on MusicBrainz has 16 tracks on the 2nd disc. Are you sure you have the exact same release? Might be that there is a version of this album that is not registered in MusicBrainz yet.

**Comment by JoeLametta** [comment]
> Might be that there is a version of this album that is not registered in MusicBrainz yet.

That seems it.
In case of no reply I'll close the issue in 2 weeks.

**Comment by Freso** [comment]
For the record, MusicBrainz is a collaborative user edited database. https://musicbrainz.org/doc/How_to_Add_a_Release has information on how to add releases. :)
