### ISSUE TITLE
Is it possible to limit the files produced by whipper (log, toc, m3u, cue)

### ISSUE THREAD

**Issue by nathanbibb** [whipper-team/whipper#484]
In my use case, I use whipper to rip CDs to FLAC, then use MusicBrainz Picard to manually go through the rips to make adjustments if necessary.

Because I change the names of many files in this process, any m3u files generated are no longer valid.  I would like to have an option on the command line to NOT generate the m3u.  Is that possible?

Also, if anyone has suggestions on an improvement to my process, let me know.  My high-level purpose here is to make archival copies of my CD collection so I can get rid of them.

Thanks,
Nathan

**Comment by nathanbibb** [comment]
I have one other question before I close this - is it possible to "regenerate" the files whipper produces (.cue, .log, .toc, .m3u) when file names are changed?

Here is my use case:
1. Whipper does not find an entry for a CD in the MusicBrainz database
2. I continue ripping, files are named "Unknown"
3. I later add the TOC or Release entry in MusicBrainz
4. I use Picard to rename my flac files
...Now all the files produced by whipper have the wrong filenames.

Would a better workflow be to not rip Unknown releases, and enter the data/TOC in MusicBrainz before ripping, maybe?

**Comment by nathanbibb** [comment]
Thanks for the response.  I think that answers my questions - I'll close this issue.

**Comment by peioe** [comment]
Curious, why would you vote against it ? M3U files are pretty much useless, they don't contain anything useful and most of the time they will even be wrong if anything has been renamed.

**Comment by thenktor** [comment]
@peioe Full Ack. 
M3U files remind me of Winamp 2.91 :grin: Really useless nowadays.
