### ISSUE TITLE
Allow configuring whether to auto close the drive's tray

### ISSUE THREAD

**Issue by rrdaud** [whipper-team/whipper#488]
It seems there's no option to skip "eject -t" from trying to close the tray, even when the drive doesn't have any.
This outputs an error on every rip operation: "WARNING:whipper.program.utils:command 'eject -t /dev/sr0' returned with exit code '1'".

**Comment by JoeLametta** [comment]
Hi, it should be already possible to avoid running the `eject` command of the  using the `-e` / `--eject` option like this:

```
whipper -e never cd rip
```

Please let me know if it works. :wink:

**Comment by rrdaud** [comment]
It does not work, unfortunately.

The **--eject parameter regulates whether to eject the disc after** the ripping is complete (which I still want to happen).

The command I'm trying to avoid is the **eject -t**, or trying to close the tray,** before** ripping starts.

The reason is simple: there's no tray to close, so the warning is expected, unhelpful and annoying in an otherwise flawless program.

**Comment by JoeLametta** [comment]
Thanks for the clarification.
I agree this is a needed feature: it has been scheduled for [milestone 1.0](https://github.com/whipper-team/whipper/milestone/1)

**Comment by rrdaud** [comment]
Thank you, much appreciatted!
