### ISSUE TITLE
[Feature Request] (RubyRipper) GUI for whipper?

### ISSUE THREAD

**Issue by cRaZy-bisCuiT** [whipper-team/whipper#493]
Hi folks!

I'm personally a big fan of cli programs, so I do not ask this feature for myself: Do you think having a GUI would be a viable option for whipper? I guess like that it might be more widely used.

In the past, there was a program called RupyRipper. I guess the developement faded, maybe using that gui as a base and adopting it to whipper might be an interesting move?

**Comment by JoeLametta** [comment]
Hi, this issue appears to be a duplicate of #40 (it was closed, I've just reopened it).
