### ISSUE TITLE
HDCD Detection

### ISSUE THREAD

**Issue by antiantioedipus** [whipper-team/whipper#497]
Hi,

HDCDs were a gimmick back in the late 90s and early 00s. The idea was that a CD would ship with a brickwalled version for people playing it in their car, and then a special dynamic version encoded in it that could be unlocked by a special HDCD player. It was a flop, but thousands of CDs have this feature on them. The HDCD patent has since expired and free software identifiers and decoders exist inside ffmpeg and libhdcd (you can even decode them after they're ripped and converted to FLAC).

However, many of these releases never advertised the fact they were HDCDs at all... so a lot of people own CDs with a hidden quality boost on them that they can unlock for free. It would be very useful for the purpose of both listening and archiving metadata if there was some way to automatically detect if a CD had HDCD features and perhaps note that on the log, whether this is just a notification that "this might be an HDCD" or a detailed breakdown like the foobar HDCD plugin that notes if it changes the gain, peaks, or veil. They sometimes show up in peculiar places, like one disc in a box set having this feature and the rest lacking it, and this isn't noted on the box or website anywhere, so this only gets discovered two decades later when somebody tests it on a whim... having this easily detected would be handy for people who are trying to hunt and document all of these elusive things,

Thanks

**Comment by JoeLametta** [comment]
Hi, in order to detect HDCD the ripped audio of each track needs to be checked against the presence of HDCD packets. That's why I think this feature request is out of scope for whipper: you can easily do that (for example with a script) after the rip has been completed.
