### ISSUE TITLE
Can't find drive offset

### ISSUE THREAD

**Issue by DarthGandalf** [whipper-team/whipper#503]
The drive is Optiarc - DVD RW AD-7241S and listed in http://www.accuraterip.com/driveoffsets.htm but `offset find` says `ERROR:whipper.common.accurip:error retrieving AccurateRip entry: 404 Not Found <Response [404]>`

**Comment by DarthGandalf** [comment]
[whipper.log.gz](https://github.com/whipper-team/whipper/files/5042781/whipper.log.gz)

**Comment by DarthGandalf** [comment]
Gentoo Linux

```
$ uname -a
Linux komputer 5.4.40-x86_64 #1 SMP Sat Jul 4 01:36:28 IST 2020 x86_64 AMD Ryzen 9 3900X 12-Core Processor AuthenticAMD GNU/Linux

$ equery l whipper
 * Searching for whipper ...
[IP-] [  ] media-sound/whipper-0.9.0:0
```

**Comment by MerlijnWajer** [comment]
What CD are you using?

**Comment by DarthGandalf** [comment]
The Realms of Fire and Death, by Ignea

**Comment by DarthGandalf** [comment]
Does offset depend on the CD?

**Comment by MerlijnWajer** [comment]
It does not - the offset is constant. But offset finding depends on the CD. If the CD is unknown, then you might get 404 hits. It's recommended to pick a popular CD.

**Comment by DarthGandalf** [comment]
Ok, thanks, offset finding worked with another CD (though offset found is different from the one listed in http://www.accuraterip.com/driveoffsets.htm). I find it strange that to rip a CD one needs to have some unrelated CD.

Do you know how to add CD entry to AccurateRip?

**Comment by MerlijnWajer** [comment]
If the offset is different from what is listed - perhaps you can try it with one more CD and see what that results in. What offset did whipper give you?

**Comment by MerlijnWajer** [comment]
The reason you need a relatively well known CD is that for accuraterip to work, you need others to have submitted records for the CD you are using.

**Comment by DarthGandalf** [comment]
The offset reported by whipper is 48 with several other CDs. And, looking at my old EAC rips, it was also using offset 48. Probably the textual table at http://www.accuraterip.com/driveoffsets.htm is outdated... I never needed to specifically find the offset with EAC though. Perhaps because first CD I ripped with it was already popular enough?

Does whipper have an option of submitting the record?

**Comment by JoeLametta** [comment]
> The drive is Optiarc - DVD RW AD-7241S
> [...]
> Ok, thanks, offset finding worked with another CD (though offset found is different from the one listed in http://www.accuraterip.com/driveoffsets.htm).
> [...]
> The offset reported by whipper is 48 with several other CDs. And, looking at my old EAC rips, it was also using offset 48. Probably the textual table at http://www.accuraterip.com/driveoffsets.htm is outdated...

Well, what I see in that table is this (which seems to match with what whipper reports):

| CD Drive                | Correction Offset | Submitted By | Percentage Agree |
| :---:                   | :---:             | :---:        | :---:            |
Optiarc - DVD RW AD-7241S | 48                | 530          | 100%             |

That same offset `48` is included in [DAEFeatures.co.uk](https://www.daefeatures.co.uk/)'s database ([link](https://www.daefeatures.co.uk/search?manufacturer=38&model=AD-7241S&accurate_stream=All&caching=All&c2=All&htoa=All&overread=All)):

| Manufacturer | Model    | Type    | Firmware | Accurate Stream | Caching | C2 Errors | HTOA  | Overread | Sample Offset | Write Offset | Submitted By                                    |
| :---:        | :---:    | :---:   | :---:    | :---:           | :---:   | :---:     | :---: | :---:    | :---:         | :---:        | :---:                                           |
| Optiarc      | AD-7241S | DVD+-RW | 1.03     | Yes             | No      | Yes       | No    | None     | +48           |              | z                                               |
| Optiarc      | AD-7241S | DVD+-RW | -        |                 |         |           |       |          | +48           |              | [dbpoweramp](https://www.dbpoweramp.com/) (255) |

> Does whipper have an option of submitting the record?

Unfortunately that isn't possible as it's not allowed: https://github.com/whipper-team/whipper/issues/36#issuecomment-248000288

**Comment by DarthGandalf** [comment]
Ah, I was looking at the number `530` instead :(

Alright, thanks!
