### ISSUE TITLE
path_filter_whitespace not working

### ISSUE THREAD

**Issue by wararjey** [whipper-team/whipper#513]
I have a config file like this:

```[main]
path_filter_dot = True
path_filter_posix = True
path_filter_vfat = True
path_filter_whitespace = True
path_filter_printable = False

[whipper.cd.rip]
unknown = False
output_directory = /path/to/output_directory
track_template = %%A/%%y-%%d/%%t-%%n
disc_template =  %%A/%%y-%%d/%%A-%%d
```
I would expect that the output files have all spaces replaced by the underscore. However, the spaces do not get removed.

Is there something wrong with my config file or is this a bug?

Regards,

**Comment by JoeLametta** [comment]
> Is there something wrong with my config file or is this a bug?

I've done a quick test and it looks like a bug.
