### ISSUE TITLE
Feature Request: Add `-d` | `--device` option to `whipper offset find`

### ISSUE THREAD

**Issue by Bujiraso** [whipper-team/whipper#527]
Multiple whipper commands take a drive as an option, but `whipper offset find` does not.
This is simply a feature to ensure the user can specify the drive for whipper offset find.

The priority of this is low as it is a "run once" sort of thing that is not very highly used.

That being said, I'm currently using whipper on the other drive and noticed that I can't specify which drive to choose -- I worked around this issue by ensuring there was only one disc loaded but it would be good to have the parameter to specify so that such work-arounds aren't needed.

There are cases where whipper may already be able to guess the drive -- and this is fine -- so this would act as a point of sanity for the user and an override in odd cases.

**Comment by Bujiraso** [comment]
Whipper may actually only take /dev/sr0 here, so if you had two drives I'm not sure how to tell it to use /dev/sr1... The work-around might be to swap the hardware connections, making this a little more interesting of a request

**Comment by mtdcr** [comment]
This feature already exists since v0.4.1.

```
$ whipper offset find -h
usage: whipper offset find [-h] [-o OFFSETS] [-d DEVICE]

Find drive's read offset by ripping tracks from a CD in the AccurateRip database.

optional arguments:
  -h, --help            show this help message and exit
  -o OFFSETS, --offsets OFFSETS
                        list of offsets, comma-separated, colon-separated for ranges (default: +6,
                        +667, +48, +102, +12, +30, +103, +618, +96, +594, +738, +98, -472, +116,
                        +733, +696, +120, +691, +685, +99, +97, +600, +676, +690, +1292, +702, +686,
                        -24, +704, +697, +572, +1182, +688, +91, -491, +145, +689, +564, +708, +86,
                        +355, +79, -496, +679, -1164, 0, +1160, -436, +694, +684, +94, +1194, +106,
                        +681, +117, +692, +943, +92, +680, +678, +682, +1268, +1279, +1473, -582,
                        -54, +674, +687, +1272, +1263, +1508, +675, +534, +740, +122, -489, +974,
                        +976, +1303, +108, +1130, +111, +739, +732, -589, -495, -494, +975, +961,
                        +935, +87, +668, +234, +1776, +138, +1364, +1336, +1262, +1127)
  -d DEVICE, --device DEVICE
                        CD-DA device (default: /dev/cdrom)
```

**Comment by JoeLametta** [comment]
I confirm what @mtdcr said: this is mentioned in the [relevant manpage](https://github.com/whipper-team/whipper/blob/develop/man/whipper-offset-find.rst) too.

**Comment by Bujiraso** [comment]
I missed this one, thanks all!
