### ISSUE TITLE
Switch official IRC channel off of freenode

### ISSUE THREAD

**Issue by Freso** [whipper-team/whipper#540]
freenode has experienced a hostile takeover. Pretty much all staff has resigned and the hardware freenode is using was on agreements with individual staffers, so no telling if freenode will even continue to function for much longer. https://gist.github.com/joepie91/df80d8d36cd9d1bde46ba018af497409 has some information on it.

Most freenode staff has moved to found [Libera.Chat](https://libera.chat/) and I would suggest we move the official `#whipper` channel to there as well.

(I have already registered the channel on LC, so it’s safe if we decide to do so.)

Please react to this issue with a :+1: if you are for moving over to Libera.Chat and :-1: if you are against. Questions and discussion in comments. :)

**Comment by MerlijnWajer** [comment]
Fine with doing it. Afraid to lose the amount of people we have there, but it's fudged if we do, fudged if we don't.

**Comment by Freso** [comment]
Yeah. It’s a bad situation. :\ FWIW, it seems like a lot of projects/people/channels are moving over. (I’m also going to propose on Monday that MetaBrainz moves over officially.)
