### ISSUE TITLE
submitting to accurip database

### ISSUE THREAD

**Issue by mrturcot** [whipper-team/whipper#567]
Does whipper submit to accurip database? Or just verify with it. Thanks.

BTW awesome project, finally I dont need to boot into windows to use eac :)

**Comment by MerlijnWajer** [comment]
No, the AR database does not have a public API for submitting AFAIK, and it also requires keys that likely will not be given to Whipper. So whipper only verifies the entries in the AR database. (If it did accept submissions from non-verified-software, I would probably have about 300,000 records to submit.)

**Comment by mrturcot** [comment]
lol ah ok got it, thanks a lot for explaning, cheers man!
