### ISSUE TITLE
add manpage

### ISSUE THREAD

**Issue by RecursiveForest** [whipper-team/whipper#73]
What form this takes needs to come after we remove python-command.

**Comment by MerlijnWajer** [comment]
The way I usually write manpages is by writing a document in restructured text, and then use rst2man. May be useful here as well?

**Comment by MerlijnWajer** [comment]
The nice thing with rst/sphinx is that you can also have it automatically include docstrings from your code.

**Comment by MerlijnWajer** [comment]
I will take an initial stab at a makefile generated from a .rst file - if that's OK with everyone.

**Comment by RecursiveForest** [comment]
I don't mind but I also don't see the problem with writing roff either. I say go for it, if the results are good then it'll be fine by me.

**Comment by MerlijnWajer** [comment]
Right. I'll do this soon.
